Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2019-11, with the labels that each got.

#433 Edited OERCONE ioc to boot using lua, calling scripts from the utilities support modules
  OERCONE/OERCONE-IOC-01App/src/OERCONE-IOC-01Main.cpp
  OERCONE/OERCONE-IOC-01App/src/build.mak
  OERCONE/configure/RELEASE
  OERCONE/iocBoot/iocOERCONE-IOC-01/st-common.cmd
  OERCONE/iocBoot/iocOERCONE-IOC-01/st-common.lua
Labels: size/L

#416 Ticket 4665 - add linmot emulator
  LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd
Labels: size/S

#435 Ticket 4834 - Gamry IOC description update
  GAMRY/iocBoot/iocGAMRY-IOC-01/config.xml
Labels: size/XS

#438 Fix linux static link
  Makefile
  OERCONE/OERCONE-IOC-01App/src/build.mak
Labels: size/XS

#434 Ticket651 add ioc cryosms
  CRYOSMS/CRYOSMS-IOC-01App/Makefile
  CRYOSMS/CRYOSMS-IOC-01App/src/CRYOSMS-IOC-01Main.cpp
  CRYOSMS/CRYOSMS-IOC-01App/src/Makefile
  CRYOSMS/CRYOSMS-IOC-01App/src/build.mak
  CRYOSMS/CRYOSMS-IOC-02App/Makefile
  CRYOSMS/CRYOSMS-IOC-02App/src/CRYOSMS-IOC-02Main.cpp
  CRYOSMS/CRYOSMS-IOC-02App/src/Makefile
  CRYOSMS/Makefile
  CRYOSMS/configure/CONFIG
  CRYOSMS/configure/CONFIG_SITE
  CRYOSMS/configure/Makefile
  CRYOSMS/configure/RELEASE
  CRYOSMS/configure/RULES
  CRYOSMS/configure/RULES.ioc
  CRYOSMS/configure/RULES_DIRS
  CRYOSMS/configure/RULES_TOP
  CRYOSMS/iocBoot/Makefile
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/Makefile
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st.cmd
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-02/Makefile
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-02/config.xml
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-02/st.cmd
Labels: size/L

#439 Add cryosms to top level make
  Makefile
Labels: size/XS

#440 Fix linux link
  CRYOSMS/CRYOSMS-IOC-01App/src/build.mak
Labels: size/XS

#437 Ticket4831 cryosms simple start
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd
Labels: size/L

#441 Updated CRYOSMS library name
  CRYOSMS/CRYOSMS-IOC-01App/src/build.mak
Labels: size/XS

#442 Revert "Ticket4831 cryosms simple start"
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd
Labels: size/M
