Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2019-12, with the labels that each got.

#444 Ticket 5028: Added alarm for cryovalve
  CRYVALVE/CRYVALVE-IOC-01App/Db/CRYVALVE.db
Labels: size/XS

#445 Ticket3876 muon ice fridge
  ICEFRDGE/ICEFRDGE-IOC-01App/Db/Makefile
  ICEFRDGE/ICEFRDGE-IOC-01App/Makefile
  ICEFRDGE/ICEFRDGE-IOC-01App/src/ICEFRDGE-IOC-01Main.cpp
  ICEFRDGE/ICEFRDGE-IOC-01App/src/Makefile
  ICEFRDGE/ICEFRDGE-IOC-01App/src/build.mak
  ICEFRDGE/ICEFRDGE-IOC-02App/Db/Makefile
  ICEFRDGE/ICEFRDGE-IOC-02App/Makefile
  ICEFRDGE/ICEFRDGE-IOC-02App/src/ICEFRDGE-IOC-02Main.cpp
  ICEFRDGE/ICEFRDGE-IOC-02App/src/Makefile
  ICEFRDGE/Makefile
  ICEFRDGE/configure/CONFIG
  ICEFRDGE/configure/CONFIG_SITE
  ICEFRDGE/configure/Makefile
  ICEFRDGE/configure/RELEASE
  ICEFRDGE/configure/RULES
  ICEFRDGE/configure/RULES.ioc
  ICEFRDGE/configure/RULES_DIRS
  ICEFRDGE/configure/RULES_TOP
  ICEFRDGE/iocBoot/Makefile
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/Makefile
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/config.xml
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/st-common.cmd
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/st.cmd
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-02/Makefile
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-02/config.xml
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-02/st.cmd
  Makefile
Labels: size/XL

#449 modify st
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/config.xml
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/st.cmd
Labels: size/S

#443 Ticket4838 zero field strength
  Makefile
  ZFMAGFLD/Makefile
  ZFMAGFLD/ZFMAGFLD-IOC-01App/Db/Makefile
  ZFMAGFLD/ZFMAGFLD-IOC-01App/Makefile
  ZFMAGFLD/ZFMAGFLD-IOC-01App/protocol/Makefile
  ZFMAGFLD/ZFMAGFLD-IOC-01App/src/Makefile
  ZFMAGFLD/ZFMAGFLD-IOC-01App/src/ZFMAGFLD-IOC-01Main.cpp
  ZFMAGFLD/ZFMAGFLD-IOC-01App/src/build.mak
  ZFMAGFLD/configure/CONFIG
  ZFMAGFLD/configure/CONFIG_SITE
  ZFMAGFLD/configure/Makefile
  ZFMAGFLD/configure/RELEASE
  ZFMAGFLD/configure/RULES
  ZFMAGFLD/configure/RULES.ioc
  ZFMAGFLD/configure/RULES_DIRS
  ZFMAGFLD/configure/RULES_TOP
  ZFMAGFLD/iocBoot/Makefile
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/Makefile
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd
Labels: size/L

#447 Ticket4855 muon zero field controller
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
  Makefile
  ZFCNTRL/Makefile
  ZFCNTRL/ZFCNTRL-IOC-01App/Makefile
  ZFCNTRL/ZFCNTRL-IOC-01App/src/Makefile
  ZFCNTRL/ZFCNTRL-IOC-01App/src/ZFCNTRL-IOC-01Main.cpp
  ZFCNTRL/ZFCNTRL-IOC-01App/src/build.mak
  ZFCNTRL/configure/CONFIG
  ZFCNTRL/configure/CONFIG_SITE
  ZFCNTRL/configure/Makefile
  ZFCNTRL/configure/RELEASE
  ZFCNTRL/configure/RULES
  ZFCNTRL/configure/RULES.ioc
  ZFCNTRL/configure/RULES_DIRS
  ZFCNTRL/configure/RULES_TOP
  ZFCNTRL/iocBoot/Makefile
  ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/Makefile
  ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/config.xml
  ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/st.cmd
Labels: size/L

#452 Add missing gsl library
  ZFMAGFLD/ZFMAGFLD-IOC-01App/src/build.mak
Labels: size/XS
