Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-11, with the labels that each got.

#540 Ticket3185 remote mode reliability
  KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
Labels: size/XS

#545 Ticket 5661: Added ReadAscii Ramping to Kepco IOC
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
  ITC503/iocBoot/iocITC503-IOC-01/st-common.cmd
  KEPCO/KEPCO-IOC-01App/src/build.mak
  KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
  TRITON/iocBoot/iocTRITON-IOC-01/st-common.cmd
Labels: size/S

#552 Changed TEKMSO4104 dependencies to be more explicit
  TEKMSO4104B/configure/RELEASE
Labels: size/S

#548 Ticket5663: HTS Smart Monitor
  Makefile
  SMRTMON/Makefile
  SMRTMON/SMRTMON-IOC-01App/Db/Makefile
  SMRTMON/SMRTMON-IOC-01App/Makefile
  SMRTMON/SMRTMON-IOC-01App/protocol/Makefile
  SMRTMON/SMRTMON-IOC-01App/src/Makefile
  SMRTMON/SMRTMON-IOC-01App/src/SMRTMON-IOC-01Main.cpp
  SMRTMON/SMRTMON-IOC-01App/src/build.mak
  SMRTMON/configure/CONFIG
  SMRTMON/configure/CONFIG_SITE
  SMRTMON/configure/Makefile
  SMRTMON/configure/RELEASE
  SMRTMON/configure/RULES
  SMRTMON/configure/RULES.ioc
  SMRTMON/configure/RULES_DIRS
  SMRTMON/configure/RULES_TOP
  SMRTMON/iocBoot/Makefile
  SMRTMON/iocBoot/iocSMRTMON-IOC-01/Makefile
  SMRTMON/iocBoot/iocSMRTMON-IOC-01/config.xml
  SMRTMON/iocBoot/iocSMRTMON-IOC-01/st-common.cmd
  SMRTMON/iocBoot/iocSMRTMON-IOC-01/st.cmd
Labels: size/L

#551 Ticket 5836: Fix autosave for GALILMUL
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALILMUL_01_positions.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALILMUL_01_settings.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALIL_01_positions.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALIL_01_settings.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/IMATStagesMenu.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-common.cmd
Labels: size/S

#554 Set default to 0
  KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
Labels: size/XS

#553 Fix ioc system tests
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-common.cmd
Labels: size/XS

#555 Remove invalid characters
  FINS/FINS-IOC-01App/Db/larmor-air-header.template
Labels: size/XS

#556 remove degrees symbol
  FZJDDFCH/FZJDDFCH-IOC-01App/Db/FZJDDFCH.db
Labels: size/S

#549 Ticket5494
  TIZR/Makefile
  TIZR/TIZR-IOC-01App/Db/Makefile
  TIZR/TIZR-IOC-01App/Makefile
  TIZR/TIZR-IOC-01App/protocol/Makefile
  TIZR/TIZR-IOC-01App/src/Makefile
  TIZR/TIZR-IOC-01App/src/TIZR-IOC-01Main.cpp
  TIZR/TIZR-IOC-01App/src/build.mak
  TIZR/TIZR-IOC-02App/Db/Makefile
  TIZR/TIZR-IOC-02App/Makefile
  TIZR/TIZR-IOC-02App/src/Makefile
  TIZR/TIZR-IOC-02App/src/TIZR-IOC-02Main.cpp
  TIZR/configure/CONFIG
  TIZR/configure/CONFIG_SITE
  TIZR/configure/Makefile
  TIZR/configure/RELEASE
  TIZR/configure/RULES
  TIZR/configure/RULES.ioc
  TIZR/configure/RULES_DIRS
  TIZR/configure/RULES_TOP
  TIZR/iocBoot/Makefile
  TIZR/iocBoot/iocTIZR-IOC-01/Makefile
  TIZR/iocBoot/iocTIZR-IOC-01/config.xml
  TIZR/iocBoot/iocTIZR-IOC-01/st-common.cmd
  TIZR/iocBoot/iocTIZR-IOC-01/st.cmd
  TIZR/iocBoot/iocTIZR-IOC-02/Makefile
  TIZR/iocBoot/iocTIZR-IOC-02/config.xml
  TIZR/iocBoot/iocTIZR-IOC-02/st.cmd
Labels: size/L

#550 Ticket 5662: Added magnet calibration for KEPCOs
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
  KEPCO/KEPCO-IOC-01App/src/build.mak
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
Labels: size/L

#558 Fix static build by being explicit about all dependencies
  KEPCO/KEPCO-IOC-01App/src/build.mak
Labels: size/XS

#542 Ticket5296 danfysik polarity
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_8000_status.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_8500_status.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_8800_status.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_polarity.db
  DFKPS/DFKPS-IOC-01App/Db/Makefile
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-8000.cmd
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-8500.cmd
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-8800.cmd
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd
  RKNPS/RKNPS-IOC-01App/Db/DFKPS_RIKEN.db
Labels: size/L
