Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-08, with the labels that each got.

#403 Added loading a .db file from the instrument's config
  INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd
Labels: size/XS

#529 Allow . in card macro names
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
Labels: size/S

#531 Fix library order for linux static
  KHLY2001/KHLY2001-IOC-01App/src/build.mak
Labels: size/XS

#532 Ticket5637 sans2d testing fixes
  FINS/FINS-IOC-01App/Db/address-read.template
  FINS/FINS-IOC-01App/Db/read-bits.template
  FINS/FINS-IOC-01App/Db/sans2d-general-status.template
Labels: size/S

#530 Ticket4586
  INHIBITR/INHIBITR-IOC-01App/src/inhibitor.st
  INHIBITR/iocBoot/iocINHIBITR-IOC-01/st.cmd
Labels: size/L
