Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-07, with the labels that each got.

#480 Check in conditional load code from LOQ
  RUNCTRL/README.md
  RUNCTRL/RUNCTRL_01App/Db/LOQ_detector.db
  RUNCTRL/RUNCTRL_01App/Db/alertAction.db
  RUNCTRL/RUNCTRL_01App/Db/runcontrol.substitutions
  RUNCTRL/RUNCTRL_01App/Db/runcontrolMgr.substitutions
  RUNCTRL/iocBoot/iocRUNCTRL_01/st.cmd
Labels: size/M

#512 Binary record to tell us if vessel is under vacuum
  FINS/FINS-IOC-01App/Db/sans2d-vac-status.template
Labels: size/S

#513 Ticket4580 sans2d vacuum tank detector baffle indicator
  FINS/FINS-IOC-01App/Db/sans2d-vac-intervals.template
  FINS/FINS-IOC-01App/Db/sans2d-vacuum.substitutions
  FINS/iocBoot/iocFINS-IOC-01/config.xml
Labels: size/S

#511 Ticket4594 superlogics
  SPRLG/SPRLG-IOC-01App/Db/Makefile
  SPRLG/SPRLG-IOC-01App/Db/superlogics.substitutions
  SPRLG/SPRLG-IOC-01App/protocol/Makefile
  SPRLG/iocBoot/iocSPRLG-IOC-01/config.xml
  SPRLG/iocBoot/iocSPRLG-IOC-01/st-common.cmd
Labels: size/M

#502 Ticket5365
  MECFRF/MECFRF-IOC-01App/Makefile
  MECFRF/MECFRF-IOC-01App/src/MECFRF-IOC-01Main.cpp
  MECFRF/MECFRF-IOC-01App/src/Makefile
  MECFRF/MECFRF-IOC-01App/src/build.mak
  MECFRF/MECFRF-IOC-02App/Makefile
  MECFRF/MECFRF-IOC-02App/src/MECFRF-IOC-02Main.cpp
  MECFRF/MECFRF-IOC-02App/src/Makefile
  MECFRF/Makefile
  MECFRF/configure/CONFIG
  MECFRF/configure/CONFIG_SITE
  MECFRF/configure/Makefile
  MECFRF/configure/RELEASE
  MECFRF/configure/RULES
  MECFRF/configure/RULES.ioc
  MECFRF/configure/RULES_DIRS
  MECFRF/configure/RULES_TOP
  MECFRF/iocBoot/Makefile
  MECFRF/iocBoot/iocMECFRF-IOC-01/Makefile
  MECFRF/iocBoot/iocMECFRF-IOC-01/config.xml
  MECFRF/iocBoot/iocMECFRF-IOC-01/st-common.cmd
  MECFRF/iocBoot/iocMECFRF-IOC-01/st.cmd
  MECFRF/iocBoot/iocMECFRF-IOC-02/Makefile
  MECFRF/iocBoot/iocMECFRF-IOC-02/config.xml
  MECFRF/iocBoot/iocMECFRF-IOC-02/st.cmd
  Makefile
Labels: size/L

#516 Ticket4596 sans2d little jaws
  GALILMUL/Doxyfile
  GALILMUL/GALILMUL-IOC-01App/Db/Makefile
  GALILMUL/GALILMUL-IOC-01App/Db/galil_analog_ports.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_coordinate_systems.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_ctrl_extras.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_digital_ports.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_motor.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_motor_extras.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_profileMoveAxis.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_profileMoveController.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_userdef_records.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_userdef_records8.substitutions
  GALILMUL/GALILMUL-IOC-01App/Makefile
  GALILMUL/GALILMUL-IOC-01App/src/GALILMUL-IOC-01Main.cpp
  GALILMUL/GALILMUL-IOC-01App/src/Makefile
  GALILMUL/GALILMUL-IOC-01App/src/build.mak
  GALILMUL/GALILMUL-IOC-02App/Db/Makefile
  GALILMUL/GALILMUL-IOC-02App/Makefile
  GALILMUL/GALILMUL-IOC-02App/src/GALILMUL-IOC-02Main.cpp
  GALILMUL/GALILMUL-IOC-02App/src/Makefile
  GALILMUL/MainPage.dox
  GALILMUL/Makefile
  GALILMUL/configure/CONFIG
  GALILMUL/configure/CONFIG_SITE
  GALILMUL/configure/Makefile
  GALILMUL/configure/RELEASE
  GALILMUL/configure/RULES
  GALILMUL/configure/RULES.ioc
  GALILMUL/configure/RULES_DIRS
  GALILMUL/configure/RULES_TOP
  GALILMUL/iocBoot/Makefile
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/0.0.0.0.gmc
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/0.0.0.0_gen.gmc
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALIL_01_positions.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALIL_01_settings.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/IMATStagesMenu.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/Makefile
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/README_galil_cmd.txt
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/config.xml
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/galildb.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/motorsim.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-axis.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-common.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-motor-controller.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-02/GALIL_02_positions.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-02/GALIL_02_settings.req
  GALILMUL/iocBoot/iocGALILMUL-IOC-02/Makefile
  GALILMUL/iocBoot/iocGALILMUL-IOC-02/config.xml
  GALILMUL/iocBoot/iocGALILMUL-IOC-02/st.cmd
Labels: size/XXL

#520 Add galilmul to top level makefile
  Makefile
Labels: size/XS

#522 Disable GALILMUL on linux
  Makefile
Labels: size/XS

#482 Enable PVA and Kafka for liveview
  ISISDAE/ISISDAE-IOC-01App/src/build.mak
  ISISDAE/configure/RELEASE
  ISISDAE/iocBoot/iocISISDAE-IOC-01/liveview.cmd
  ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd
  NGEM/NGEM-IOC-01App/src/build.mak
  NGEM/configure/RELEASE
  NGEM/iocBoot/iocNGEM-IOC-01/st-common.cmd
Labels: size/M

#518 Send separate change message for alerts
  RUNCTRL/RUNCTRL_01App/Db/alertAction.db
  RUNCTRL/RUNCTRL_01App/Db/runcontrolMgr.substitutions
  RUNCTRL/check_rc_pvs.bat
  RUNCTRL/iocBoot/iocRUNCTRL_01/st.cmd
Labels: size/M

#525 Fix vs2010 and linux builds
  ISISDAE/ISISDAE-IOC-01App/src/build.mak
  NGEM/NGEM-IOC-01App/src/build.mak
Labels: size/S

#519 Ticket5452 refl macros
  Makefile
  REFL/Makefile
  REFL/iocBoot/iocREFL-IOC-01/Makefile
  REFL/iocBoot/iocREFL-IOC-01/config.xml
  REFL/iocBoot/iocREFL-IOC-01/dllPath.bat
  REFL/iocBoot/iocREFL-IOC-01/runIOC.bat
Labels: size/M

#523 Add FINS logic to set unknown to string and error severity
  FINS/FINS-IOC-01App/Db/sans2d-vac-status.template
Labels: size/M

#526 Enable VISADrv on Linux
  Makefile
Labels: size/XS

#524 Ticket5333 helium recovery plc ioc
  FINS/FINS-IOC-01App/Db/he-recovery-alarm.template
  FINS/FINS-IOC-01App/Db/he-recovery-auto-manual.template
  FINS/FINS-IOC-01App/Db/he-recovery-dword.template
  FINS/FINS-IOC-01App/Db/he-recovery-header.template
  FINS/FINS-IOC-01App/Db/he-recovery-int.template
  FINS/FINS-IOC-01App/Db/he-recovery-real.template
  FINS/FINS-IOC-01App/Db/he-recovery-valve.template
  FINS/FINS-IOC-01App/Db/he-recovery.db
  FINS/FINS-IOC-01App/Db/he-recovery.substitutions
  FINS/exampleSettings/HELIUM_RECOVERY/FINS_01.cmd
  FINS/iocBoot/iocFINS-IOC-01/config.xml
Labels: size/XL
