Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-04, with the labels that each got.

#477 Ticket 4919: Update tcIOC to specify PLC version
  TWINCAT/iocBoot/iocTWINCAT-IOC-01/config.xml
  TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua
Labels: size/M

#495 Fix tests
  FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db
Labels: size/XS

#494 Add VS2015 debug libraries if needed
  ISISDAE/iocBoot/iocISISDAE-IOC-01/dllPath_extra.bat
Labels: size/S

#479 Add background script runner
  BGRSCRPT/Makefile
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/config.xml
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/runIOC.bat
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-02/config.xml
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-02/runIOC.bat
Labels: size/M

#499 Fix build
  Makefile
Labels: size/XS

#496 process loop removed in KHLY2700
  KHLY2700/KHLY2700-IOC-01App/Db/keithley2700.db
Labels: size/XS

#497 Recode to fix setpoint/readback sync issue and also remove use of epicsThreadSleep
  FERMCHOP/FERMCHOP-IOC-01App/src/keep_sp_and_rbv_in_sync.st
Labels: size/M

#487 Ticket 4287: Update ROTSC from tests
  ROTSC/ROTSC-IOC-01App/src/build.mak
  ROTSC/configure/RELEASE
  ROTSC/iocBoot/iocROTSC-IOC-01/st.cmd
Labels: size/XS

#484 Improve DMA4500M IOC
  DMA4500M/DMA4500M-IOC-02App/Db/Makefile
  DMA4500M/DMA4500M-IOC-02App/Makefile
  DMA4500M/DMA4500M-IOC-02App/src/DMA4500M-IOC-02Main.cpp
  DMA4500M/DMA4500M-IOC-02App/src/Makefile
  DMA4500M/iocBoot/iocDMA4500M-IOC-01/config.xml
  DMA4500M/iocBoot/iocDMA4500M-IOC-01/st-common.cmd
  DMA4500M/iocBoot/iocDMA4500M-IOC-02/Makefile
  DMA4500M/iocBoot/iocDMA4500M-IOC-02/config.xml
  DMA4500M/iocBoot/iocDMA4500M-IOC-02/st.cmd
Labels: size/M

#493 Ticket5332 specify plc node
  FINS/FINS-IOC-01App/Db/Makefile
  FINS/FINS-IOC-01App/Db/he-recovery.db
  FINS/iocBoot/iocFINS-IOC-01/config.xml
  FINS/iocBoot/iocFINS-IOC-01/fins-sim.cmd
Labels: size/S
