Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-10, with the labels that each got.

#539 Add missing records
  ITC503/ITC503-IOC-01App/Db/ITC503.db
Labels: size/XS

#536 Force load defaults on startup
  CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd
Labels: size/XS

#544 Remove logging RAW status
  FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db
Labels: size/XS

#537 Ticket5546 little blue cryostat
  MERCURY_ITC/MERCURY-IOC-01App/Db/Makefile
  MERCURY_ITC/MERCURY-IOC-01App/src/build.mak
  MERCURY_ITC/configure/RELEASE
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
Labels: size/S

#538 Refactor LSICORR to use macros
  LSICORR/iocBoot/iocLSICORR-IOC-01/config.xml
  LSICORR/iocBoot/iocLSICORR-IOC-01/dllPath.bat
  LSICORR/iocBoot/iocLSICORR-IOC-01/runIOC.bat
  LSICORR/iocBoot/iocLSICORR-IOC-02/dllPath.bat
  LSICORR/iocBoot/iocLSICORR-IOC-02/runIOC.bat
  REFL/iocBoot/iocREFL-IOC-01/runIOC.bat
Labels: size/M

#546 Add better message
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
Labels: size/XS

#547 Move startup files from support
  MERCURY_ITC/MERCURY-IOC-01App/src/build.mak
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-common.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-level.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-pressure.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-temp-spc.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-temp.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-02/st.cmd
Labels: size/L
