Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-02, with the labels that each got.

#469 Add macro
  SMC100/iocBoot/iocSMC100-IOC-01/config.xml
Labels: size/XS

#470 Load VISA locally if not present on system
  ISISDAE/iocBoot/iocISISDAE-IOC-01/dllPath_extra.bat
Labels: size/XS

#472 Hot Fix: terminators created after port created as required by real device
  LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd
Labels: size/XS

#473 Add CAENV895 ioc
  CAENV895/CAENV895-IOC-01App/Db/Makefile
  CAENV895/CAENV895-IOC-01App/Makefile
  CAENV895/CAENV895-IOC-01App/src/CAENV895-IOC-01Main.cpp
  CAENV895/CAENV895-IOC-01App/src/Makefile
  CAENV895/CAENV895-IOC-01App/src/build.mak
  CAENV895/Makefile
  CAENV895/configure/CONFIG
  CAENV895/configure/CONFIG_SITE
  CAENV895/configure/Makefile
  CAENV895/configure/RELEASE
  CAENV895/configure/RULES
  CAENV895/configure/RULES.ioc
  CAENV895/configure/RULES_DIRS
  CAENV895/configure/RULES_TOP
  CAENV895/iocBoot/Makefile
  CAENV895/iocBoot/iocCAENV895-IOC-01/.gitignore
  CAENV895/iocBoot/iocCAENV895-IOC-01/Makefile
  CAENV895/iocBoot/iocCAENV895-IOC-01/auto_settings.req
  CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd
  CAENV895/iocBoot/iocCAENV895-IOC-01/st.cmd
  CAENV895/iocBoot/iocCAENV895-IOC-01/vmeconfigMenu.req
  Makefile
Labels: size/L

#471 Implement lakeshore 372 IOC
  LKSH372/LKSH372-IOC-01App/Makefile
  LKSH372/LKSH372-IOC-01App/src/LKSH372-IOC-01Main.cpp
  LKSH372/LKSH372-IOC-01App/src/Makefile
  LKSH372/LKSH372-IOC-01App/src/build.mak
  LKSH372/LKSH372-IOC-02App/Makefile
  LKSH372/LKSH372-IOC-02App/src/LKSH372-IOC-02Main.cpp
  LKSH372/LKSH372-IOC-02App/src/Makefile
  LKSH372/Makefile
  LKSH372/configure/CONFIG
  LKSH372/configure/CONFIG_SITE
  LKSH372/configure/Makefile
  LKSH372/configure/RELEASE
  LKSH372/configure/RULES
  LKSH372/configure/RULES.ioc
  LKSH372/configure/RULES_DIRS
  LKSH372/configure/RULES_TOP
  LKSH372/iocBoot/Makefile
  LKSH372/iocBoot/iocLKSH372-IOC-01/Makefile
  LKSH372/iocBoot/iocLKSH372-IOC-01/config.xml
  LKSH372/iocBoot/iocLKSH372-IOC-01/st-common.cmd
  LKSH372/iocBoot/iocLKSH372-IOC-01/st.cmd
  LKSH372/iocBoot/iocLKSH372-IOC-02/Makefile
  LKSH372/iocBoot/iocLKSH372-IOC-02/config.xml
  LKSH372/iocBoot/iocLKSH372-IOC-02/st.cmd
  Makefile
Labels: size/L

#476 Add motion setpoint axes etc to SMC100 and make same as SM300
  SM300/iocBoot/iocSM300-IOC-01/st-common.cmd
  SMC100/iocBoot/iocSMC100-IOC-01/st-common.cmd
Labels: size/S

#455 HIFI Cryomag: Simple Start 2
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd
Labels: size/XS

#478 Change defaults
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd
Labels: size/XS
