Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-05, with the labels that each got.

#504 Ticket 5381: Updated lua scripts to correctly scope imports
  OERCONE/iocBoot/iocOERCONE-IOC-01/st-common.lua
  TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua
Labels: size/M

#505 Add additional archiving
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_calibrated.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_polarity.db
Labels: size/XS

#506 Add PV to RKNPS allow tracking status of DAQmx connection
  RKNPS/RKNPS-IOC-01App/Db/Makefile
  RKNPS/RKNPS-IOC-01App/Db/riken_daqmx.db
  RKNPS/iocBoot/iocRKNPS-IOC-01/st.cmd
Labels: size/M

#498 Allow disabling of DFKPS AUTOONOFF PV with DISABLE_AUTOONOFF macro
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd
Labels: size/XS

#501 Ticket4555: SANS2D Vacuum System
  FINS/FINS-IOC-01App/Db/Makefile
  FINS/FINS-IOC-01App/Db/address-read.template
  FINS/FINS-IOC-01App/Db/sans2d-general-status.template
  FINS/FINS-IOC-01App/Db/sans2d-pressure-read.template
  FINS/FINS-IOC-01App/Db/sans2d-pump-add.template
  FINS/FINS-IOC-01App/Db/sans2d-pump-basics.template
  FINS/FINS-IOC-01App/Db/sans2d-pump-valve-status.template
  FINS/FINS-IOC-01App/Db/sans2d-set-point.template
  FINS/FINS-IOC-01App/Db/sans2d-vac-status.template
  FINS/FINS-IOC-01App/Db/sans2d-vacuum.substitutions
  FINS/FINS-IOC-01App/Db/write-bit.template
  FINS/exampleSettings/LARMOR_bench/FINS_01.cmd
  FINS/exampleSettings/README.md
  FINS/exampleSettings/SANS2D_vacuum/FINS_01.cmd
  FINS/iocBoot/iocFINS-IOC-01/st-common.cmd
Labels: size/XL
