Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-01, with the labels that each got.

#453 Make macros more permissive
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
Labels: size/S

#454 Use monster mode for higher data rates
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd
Labels: size/XS

#456 Pass macro through to DB
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd
Labels: size/XS

#448 Ticket1286 mercury pressure card
  MERCURY_ITC/MERCURY-IOC-01App/Db/Makefile
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-02/st.cmd
Labels: size/L

#450 Ticket5009 muon jaws
  MUONJAWS/MUONJAWS-IOC-01App/Makefile
  MUONJAWS/MUONJAWS-IOC-01App/src/MUONJAWS-IOC-01Main.cpp
  MUONJAWS/MUONJAWS-IOC-01App/src/Makefile
  MUONJAWS/MUONJAWS-IOC-01App/src/build.mak
  MUONJAWS/Makefile
  MUONJAWS/configure/CONFIG
  MUONJAWS/configure/CONFIG_SITE
  MUONJAWS/configure/Makefile
  MUONJAWS/configure/RELEASE
  MUONJAWS/configure/RULES
  MUONJAWS/configure/RULES.ioc
  MUONJAWS/configure/RULES_DIRS
  MUONJAWS/configure/RULES_TOP
  MUONJAWS/iocBoot/Makefile
  MUONJAWS/iocBoot/iocMUONJAWS-IOC-01/Makefile
  MUONJAWS/iocBoot/iocMUONJAWS-IOC-01/config.xml
  MUONJAWS/iocBoot/iocMUONJAWS-IOC-01/st.cmd
  Makefile
Labels: size/L

#458 Add 4th Kepco IOC
  KEPCO/KEPCO-IOC-04App/Db/Makefile
  KEPCO/KEPCO-IOC-04App/Makefile
  KEPCO/KEPCO-IOC-04App/protocol/Makefile
  KEPCO/KEPCO-IOC-04App/src/KEPCO-IOC-04Main.cpp
  KEPCO/KEPCO-IOC-04App/src/Makefile
  KEPCO/iocBoot/iocKEPCO-IOC-04/Makefile
  KEPCO/iocBoot/iocKEPCO-IOC-04/config.xml
  KEPCO/iocBoot/iocKEPCO-IOC-04/st.cmd
Labels: size/L

#459 Add MUONTPAR ioc
  MUONTPAR/MUONTPAR-IOC-01App/Db/Makefile
  MUONTPAR/MUONTPAR-IOC-01App/Db/muon_tpar.db
  MUONTPAR/MUONTPAR-IOC-01App/Makefile
  MUONTPAR/MUONTPAR-IOC-01App/src/MUONTPAR-IOC-01Main.cpp
  MUONTPAR/MUONTPAR-IOC-01App/src/Makefile
  MUONTPAR/MUONTPAR-IOC-01App/src/build.mak
  MUONTPAR/Makefile
  MUONTPAR/configure/CONFIG
  MUONTPAR/configure/CONFIG_SITE
  MUONTPAR/configure/Makefile
  MUONTPAR/configure/RELEASE
  MUONTPAR/configure/RULES
  MUONTPAR/configure/RULES.ioc
  MUONTPAR/configure/RULES_DIRS
  MUONTPAR/configure/RULES_TOP
  MUONTPAR/iocBoot/Makefile
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/Makefile
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd
  Makefile
Labels: size/L

#457 Ticket5043
  TDK_LAMBDA_GENESYS/GENESYS-IOC-01App/Db/TDK_Lambda_Genesys.db
  TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/config.xml
  TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/st-psu.cmd
Labels: size/L

#461 Add tolerance to config.xml
  TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/config.xml
  TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/st-psu.cmd
Labels: size/S

#463 Make axes configurable
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
Labels: size/S

#464 Load dashboard PVs from config area
  INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd
Labels: size/XS

#465 Fix Danfysik Scaling
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_calibrated.db
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
Labels: size/S

#466 Fix description of tolerance macros
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
Labels: size/XS

#462 made changes to regex for some macros to allow users to input only 40…
  CCD100/iocBoot/iocCCD100-IOC-01/config.xml
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
  TRITON/iocBoot/iocTRITON-IOC-01/config.xml
Labels: size/XS

#467 Fix IOC system tests
  LKSH460/LKSH460-IOC-01App/Db/lakeshore460_channels.template
Labels: size/XS

#468 Allow setting max voltage
  ITC503/ITC503-IOC-01App/Db/ITC503.db
Labels: size/M
