Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-12, with the labels that each got.

#557 Ticket 5688: Newport controller
  Makefile
  NWPRTXPS/Makefile
  NWPRTXPS/NWPRTXPS-IOC-01App/Db/Makefile
  NWPRTXPS/NWPRTXPS-IOC-01App/Db/motor.substitutions
  NWPRTXPS/NWPRTXPS-IOC-01App/Db/motorSim.substitutions
  NWPRTXPS/NWPRTXPS-IOC-01App/Makefile
  NWPRTXPS/NWPRTXPS-IOC-01App/src/Makefile
  NWPRTXPS/NWPRTXPS-IOC-01App/src/NWPRTXPS-IOC-01Main.cpp
  NWPRTXPS/NWPRTXPS-IOC-01App/src/build.mak
  NWPRTXPS/configure/CONFIG
  NWPRTXPS/configure/CONFIG_SITE
  NWPRTXPS/configure/Makefile
  NWPRTXPS/configure/RELEASE
  NWPRTXPS/configure/RULES
  NWPRTXPS/configure/RULES.ioc
  NWPRTXPS/configure/RULES_DIRS
  NWPRTXPS/configure/RULES_TOP
  NWPRTXPS/iocBoot/Makefile
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/Makefile
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/NWPRTXPS_01_settings.req
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/config.xml
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-axes.cmd
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-common.cmd
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-ctrl.cmd
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-max-axis.cmd
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-motor.cmd
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st.cmd
Labels: size/L

#560 Add ability to specify alarm thresholds
  ILM200/ILM200-IOC-01App/Db/ILM200_channel.db
  ILM200/iocBoot/iocILM200-IOC-01/config.xml
  ILM200/iocBoot/iocILM200-IOC-01/st-common.cmd
Labels: size/M

#562 Add ability to specifiy macros for custom_records.db
  INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd
Labels: size/XS

#567 Fix user buttons so records load correctly
  INSTETC/INSTETC-IOC-01App/Db/user_buttons.db
Labels: size/XS

#561 Ticket5029 pt2025 support
  Makefile
  PT2025/Makefile
  PT2025/PT2025-IOC-01App/Db/Makefile
  PT2025/PT2025-IOC-01App/Makefile
  PT2025/PT2025-IOC-01App/src/Makefile
  PT2025/PT2025-IOC-01App/src/PT2025-IOC-01Main.cpp
  PT2025/PT2025-IOC-01App/src/build.mak
  PT2025/PT2025-IOC-02App/Db/Makefile
  PT2025/PT2025-IOC-02App/Makefile
  PT2025/PT2025-IOC-02App/src/Makefile
  PT2025/PT2025-IOC-02App/src/PT2025-IOC-02Main.cpp
  PT2025/configure/CONFIG
  PT2025/configure/CONFIG_SITE
  PT2025/configure/Makefile
  PT2025/configure/RELEASE
  PT2025/configure/RULES
  PT2025/configure/RULES.ioc
  PT2025/configure/RULES_DIRS
  PT2025/configure/RULES_TOP
  PT2025/iocBoot/Makefile
  PT2025/iocBoot/iocPT2025-IOC-01/Makefile
  PT2025/iocBoot/iocPT2025-IOC-01/config.xml
  PT2025/iocBoot/iocPT2025-IOC-01/st-common.cmd
  PT2025/iocBoot/iocPT2025-IOC-01/st.cmd
  PT2025/iocBoot/iocPT2025-IOC-02/Makefile
  PT2025/iocBoot/iocPT2025-IOC-02/config.xml
  PT2025/iocBoot/iocPT2025-IOC-02/st.cmd
Labels: size/XL

#568 Add missing macros
  PT2025/iocBoot/iocPT2025-IOC-01/config.xml
Labels: size/XS

#569 Remove EDNEXT
  EDNEXT/EDNEXT-IOC-01App/Db/Makefile
  EDNEXT/EDNEXT-IOC-01App/Makefile
  EDNEXT/EDNEXT-IOC-01App/protocol/Makefile
  EDNEXT/EDNEXT-IOC-01App/src/EDNEXT-IOC-01Main.cpp
  EDNEXT/EDNEXT-IOC-01App/src/Makefile
  EDNEXT/EDNEXT-IOC-01App/src/build.mak
  EDNEXT/Makefile
  EDNEXT/configure/CONFIG
  EDNEXT/configure/CONFIG_SITE
  EDNEXT/configure/Makefile
  EDNEXT/configure/RELEASE
  EDNEXT/configure/RULES
  EDNEXT/configure/RULES.ioc
  EDNEXT/configure/RULES_DIRS
  EDNEXT/configure/RULES_TOP
  EDNEXT/iocBoot/Makefile
  EDNEXT/iocBoot/iocEDNEXT-IOC-01/.history
  EDNEXT/iocBoot/iocEDNEXT-IOC-01/Makefile
  EDNEXT/iocBoot/iocEDNEXT-IOC-01/st-common.cmd
  EDNEXT/iocBoot/iocEDNEXT-IOC-01/st.cmd
  Makefile
Labels: size/L

#563 Ticket5488 bump stop
  GALIL/iocBoot/iocGALIL-IOC-01/st.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st.cmd
  INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
  INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd
Labels: size/M

#570 Remove unnecessary record
  INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
Labels: size/XS
