Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2020-03, with the labels that each got.

#474 Added required voltage limit macros
  ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/config.xml
  ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/st.cmd
Labels: size/S

#483 Fix linux static build
  ROTSC/ROTSC-IOC-01App/src/build.mak
  SPRLG/SPRLG-IOC-01App/src/build.mak
Labels: size/S

#481 Adjust st.
  MEZFLIPR/iocBoot/iocMEZFLIPR-IOC-01/config.xml
  MEZFLIPR/iocBoot/iocMEZFLIPR-IOC-01/st-common.cmd
Labels: size/XS

#475 Ticket4918 sans dls
  LSICORR/Makefile
  LSICORR/iocBoot/iocLSICORR-IOC-01/Makefile
  LSICORR/iocBoot/iocLSICORR-IOC-01/config.xml
  LSICORR/iocBoot/iocLSICORR-IOC-01/runIOC.bat
  LSICORR/iocBoot/iocLSICORR-IOC-02/Makefile
  LSICORR/iocBoot/iocLSICORR-IOC-02/config.xml
  LSICORR/iocBoot/iocLSICORR-IOC-02/runIOC.bat
Labels: size/M

#489 Correct make file to include LSICORR
  Makefile
Labels: size/XS

#490 Ips fix invalid return
  FERMCHOP/FERMCHOP-IOC-01App/src/keep_sp_and_rbv_in_sync.st
  IPS/IPS-IOC-01App/src/cryomagnet.st
Labels: size/XS

#488 Ticket 4488: Removed attocube as not used
  ATTOCUBE/ATTOCUBE-IOC-01App/Db/Makefile
  ATTOCUBE/ATTOCUBE-IOC-01App/Db/common.substitutions
  ATTOCUBE/ATTOCUBE-IOC-01App/Db/single_axis.substitutions
  ATTOCUBE/ATTOCUBE-IOC-01App/Makefile
  ATTOCUBE/ATTOCUBE-IOC-01App/protocol/Makefile
  ATTOCUBE/ATTOCUBE-IOC-01App/src/ATTOCUBE-IOC-01Main.cpp
  ATTOCUBE/ATTOCUBE-IOC-01App/src/Makefile
  ATTOCUBE/ATTOCUBE-IOC-01App/src/build.mak
  ATTOCUBE/Makefile
  ATTOCUBE/configure/CONFIG
  ATTOCUBE/configure/CONFIG_SITE
  ATTOCUBE/configure/Makefile
  ATTOCUBE/configure/RELEASE
  ATTOCUBE/configure/RULES
  ATTOCUBE/configure/RULES.ioc
  ATTOCUBE/configure/RULES_DIRS
  ATTOCUBE/configure/RULES_TOP
  ATTOCUBE/iocBoot/Makefile
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/ATTOCUBE_01_axis_settings.req
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/ATTOCUBE_01_settings.req
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/Makefile
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/config.xml
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/st-common.cmd
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/st-common.lua
  ATTOCUBE/iocBoot/iocATTOCUBE-IOC-01/st.cmd
  Makefile
Labels: size/L

#492 Remove space breaking protocol
  IPS/IPS-IOC-01App/Db/ips.db
Labels: size/XS

#491 Fix recsim mode for ioc system tests
  MK2CHOPR/iocBoot/iocMK2CHOPR-IOC-01/st-common.cmd
  MK3CHOPR/MK3CHOPR-IOC-01App/Db/mk3_common.db
  MK3CHOPR/iocBoot/iocMk3CHOPR-IOC-01/st.cmd
Labels: size/XS
