Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2021-01, with the labels that each got.

#571 Ticket 2185: Updated pr template
  PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#572 Ticket 5926: Update .gitignore
  .gitignore
Labels: size/XS

#575 #4080: Add missing IOC configs
  CAENMCA/iocBoot/iocCAENMCA-IOC-01/config.xml
  CAENV895/iocBoot/iocCAENV895-IOC-01/config.xml
  EDNEXT/iocBoot/iocEDNEXT-IOC-01/config.xml
  QEPRO/iocBoot/iocQEPRO-IOC-01/config.xml
  QEPRO/iocBoot/iocQEPRO-IOC-02/config.xml
  SECI2IBEX/iocBoot/iocSECI2IBEX-IOC-01/config.xml
Labels: size/M

#566 Ticket4915 add tests
  CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd
Labels: size/S

#486 Ticket5270 fmr
  FMR/FMR-IOC-01App/Makefile
  FMR/FMR-IOC-01App/src/FMR-IOC-01Main.cpp
  FMR/FMR-IOC-01App/src/Makefile
  FMR/FMR-IOC-01App/src/build.mak
  FMR/Makefile
  FMR/configure/CONFIG
  FMR/configure/CONFIG_SITE
  FMR/configure/Makefile
  FMR/configure/RELEASE
  FMR/configure/RULES
  FMR/configure/RULES.ioc
  FMR/configure/RULES_DIRS
  FMR/configure/RULES_TOP
  FMR/iocBoot/Makefile
  FMR/iocBoot/iocFMR-IOC-01/Makefile
  FMR/iocBoot/iocFMR-IOC-01/config.xml
  FMR/iocBoot/iocFMR-IOC-01/st.cmd
Labels: size/L

#577 setting custom record macros to default to nothing
  INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd
Labels: size/XS

#576 Add FMR to makefile
  Makefile
Labels: size/XS

#579 Add functionality for MuSR
  TTIEX355P/TTIEX355P-IOC-01App/Db/ttiEX355P.db
  TTIEX355P/TTIEX355P-IOC-01App/src/build.mak
  TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/config.xml
  TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/st.cmd
Labels: size/L

#574 Add spare daq channel
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd
Labels: size/XS

#565 Use common action
  RUNCTRL/RUNCTRL_01App/Db/runcontrolMgr.substitutions
Labels: size/XS

#580 Remove stray commas
  TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/config.xml
Labels: size/XS

#559 Control alias generation
  RUNCTRL/RUNCTRL_01App/Db/runcontrol.substitutions
  RUNCTRL/iocBoot/iocRUNCTRL_01/st.cmd
Labels: size/S
