Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2021-02, with the labels that each got.

#564 Ticket5544: monitor board temperatures
  HVCAENA/HVCAENA-IOC-01App/Db/Makefile
  HVCAENA/HVCAENA-IOC-01App/Makefile
  HVCAENA/HVCAENA-IOC-01App/src/HVCAENA-IOC-01Main.cpp
  HVCAENA/HVCAENA-IOC-01App/src/Makefile
  HVCAENA/HVCAENA-IOC-01App/src/build.mak
  HVCAENA/Makefile
  HVCAENA/configure/CONFIG
  HVCAENA/configure/CONFIG_SITE
  HVCAENA/configure/Makefile
  HVCAENA/configure/RELEASE
  HVCAENA/configure/RULES
  HVCAENA/configure/RULES.ioc
  HVCAENA/configure/RULES_DIRS
  HVCAENA/configure/RULES_TOP
  HVCAENA/iocBoot/Makefile
  HVCAENA/iocBoot/iocHVCAENA-IOC-01/Makefile
  HVCAENA/iocBoot/iocHVCAENA-IOC-01/config.xml
  HVCAENA/iocBoot/iocHVCAENA-IOC-01/st.cmd
  Makefile
Labels: size/L

#582 Fix caen static
  HVCAENA/HVCAENA-IOC-01App/src/build.mak
  Makefile
Labels: size/XS

#581 Add excitations logic to lakeshore 340 IOC
  LKSH340/LKSH340-IOC-01App/src/build.mak
  LKSH340/configure/RELEASE
  LKSH340/iocBoot/iocLKSH340-IOC-01/config.xml
  LKSH340/iocBoot/iocLKSH340-IOC-01/st-common.cmd
Labels: size/S

#583 Lakeshore340: Remove incorrect comma and correct configs dir
  LKSH340/iocBoot/iocLKSH340-IOC-01/config.xml
  LKSH340/iocBoot/iocLKSH340-IOC-01/st-common.cmd
Labels: size/XS

#584 Ticket 6151: Clarify the max current is also negative
  KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
Labels: size/XS

#586 Remove no longer needed library for HVCAEN
  HVCAEN/HVCAEN-IOC-01App/src/build.mak
  HVCAEN/HVCAENSIM-IOC-01App/src/build.mak
Labels: size/S

#585 Ticket653 add ioc hifimags
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/Makefile
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags.db
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags_magnet.substitutions
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags_magnet.template
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags_temp.substitutions
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags_temp.template
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/mainpsu.db
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/switching.db
  HIFIMAGS/HIFIMAGS-IOC-01App/Makefile
  HIFIMAGS/HIFIMAGS-IOC-01App/src/HIFIMAGS-IOC-01Main.cpp
  HIFIMAGS/HIFIMAGS-IOC-01App/src/Makefile
  HIFIMAGS/HIFIMAGS-IOC-01App/src/build.mak
  HIFIMAGS/HIFIMAGS-IOC-01App/src/hifimagsys.dbd
  HIFIMAGS/HIFIMAGS-IOC-01App/src/hifimagsys.st
  HIFIMAGS/HIFIMAGS-IOC-01App/src/seqPVmacros.h
  HIFIMAGS/Makefile
  HIFIMAGS/configure/CONFIG
  HIFIMAGS/configure/CONFIG_SITE
  HIFIMAGS/configure/Makefile
  HIFIMAGS/configure/RELEASE
  HIFIMAGS/configure/RULES
  HIFIMAGS/configure/RULES.ioc
  HIFIMAGS/configure/RULES_DIRS
  HIFIMAGS/configure/RULES_TOP
  HIFIMAGS/iocBoot/Makefile
  HIFIMAGS/iocBoot/iocHIFIMAGS-IOC-01/Makefile
  HIFIMAGS/iocBoot/iocHIFIMAGS-IOC-01/config.xml
  HIFIMAGS/iocBoot/iocHIFIMAGS-IOC-01/st-common.cmd
  HIFIMAGS/iocBoot/iocHIFIMAGS-IOC-01/st.cmd
  Makefile
Labels: size/XXL

#588 Use device consistently and stop logging all asyn comms
  LINKAM95/iocBoot/iocLINKAM95-IOC-01/st-common.cmd
Labels: size/S

#590 Add smoothing to zf
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd
Labels: size/XS
