Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2021-03, with the labels that each got.

#594 Remove duplicate alias in calibration db file
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_calibrated.db
Labels: size/XS

#595 DFKPS: Use correct proto file and process records correctly
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_slew.db
Labels: size/S

#593 Load db from main GALIL area
  GALIL/GALIL-IOC-01App/Db/galil_analog_ports.substitutions
  GALIL/GALIL-IOC-01App/Db/galil_coordinate_systems.substitutions
  GALIL/GALIL-IOC-01App/Db/galil_ctrl_extras.substitutions
  GALIL/GALIL-IOC-01App/Db/galil_digital_ports.substitutions
  GALIL/GALIL-IOC-01App/Db/galil_motor.substitutions
  GALIL/GALIL-IOC-01App/Db/galil_motor_extras.substitutions
  GALIL/GALIL-IOC-01App/Db/galil_userdef_records8.substitutions
  GALIL/configure/RELEASE
  GALILMUL/GALILMUL-IOC-01App/Db/Makefile
  GALILMUL/GALILMUL-IOC-01App/Db/galil_analog_ports.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_coordinate_systems.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_ctrl_extras.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_digital_ports.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_motor.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_motor_extras.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_profileMoveAxis.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_profileMoveController.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_userdef_records.substitutions
  GALILMUL/GALILMUL-IOC-01App/Db/galil_userdef_records8.substitutions
  GALILMUL/GALILMUL-IOC-01App/src/Makefile
  GALILMUL/GALILMUL-IOC-01App/src/build.mak
  GALILMUL/GALILMUL-IOC-02App/src/Makefile
  GALILMUL/configure/RELEASE
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/galildb.cmd
Labels: size/XXL

#591 Change ramping labels and interaction with LabVIEW
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags.db
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/mainpsu.db
Labels: size/S

#587 MUONTPAR: Add an optional second tpar file
  MUONTPAR/MUONTPAR-IOC-01App/Db/muon_tpar.db
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd
Labels: size/XS

#596 adding scan for slew rate rbvs
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_slew.db
Labels: size/XS

#599 TRITON: Make poll rate configurable
  TRITON/TRITON-IOC-01App/Db/TRITON.db
  TRITON/TRITON-IOC-01App/Db/TRITON_channels.template
  TRITON/TRITON-IOC-01App/Db/TRITON_pid.template
  TRITON/TRITON-IOC-01App/Db/TRITON_pressure_channels.template
  TRITON/TRITON-IOC-01App/Db/TRITON_temp_channels.template
  TRITON/iocBoot/iocTRITON-IOC-01/config.xml
  TRITON/iocBoot/iocTRITON-IOC-01/st-common.cmd
Labels: size/M

#600 Add testing support, use db from support, remove release dep on centr…
  TEKAFG3XXX/TEKAFG3XXX-IOC-01App/Db/Makefile
  TEKAFG3XXX/TEKAFG3XXX-IOC-01App/Db/devAFG3XXX.db
  TEKAFG3XXX/configure/RELEASE
  TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st-common.cmd
  TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st.cmd
  TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-02/st.cmd
Labels: size/XXL

#601 remove icefrdge
  ICEFRDGE/ICEFRDGE-IOC-01App/Db/Makefile
  ICEFRDGE/ICEFRDGE-IOC-01App/Makefile
  ICEFRDGE/ICEFRDGE-IOC-01App/src/ICEFRDGE-IOC-01Main.cpp
  ICEFRDGE/ICEFRDGE-IOC-01App/src/Makefile
  ICEFRDGE/ICEFRDGE-IOC-01App/src/build.mak
  ICEFRDGE/ICEFRDGE-IOC-02App/Db/Makefile
  ICEFRDGE/ICEFRDGE-IOC-02App/Makefile
  ICEFRDGE/ICEFRDGE-IOC-02App/src/ICEFRDGE-IOC-02Main.cpp
  ICEFRDGE/ICEFRDGE-IOC-02App/src/Makefile
  ICEFRDGE/Makefile
  ICEFRDGE/configure/CONFIG
  ICEFRDGE/configure/CONFIG_SITE
  ICEFRDGE/configure/Makefile
  ICEFRDGE/configure/RELEASE
  ICEFRDGE/configure/RULES
  ICEFRDGE/configure/RULES.ioc
  ICEFRDGE/configure/RULES_DIRS
  ICEFRDGE/configure/RULES_TOP
  ICEFRDGE/iocBoot/Makefile
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/Makefile
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/config.xml
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/st-common.cmd
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-01/st.cmd
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-02/Makefile
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-02/config.xml
  ICEFRDGE/iocBoot/iocICEFRDGE-IOC-02/st.cmd
  Makefile
Labels: size/XL

#602 Ticket 4646 - Check default macro values
  AG33220A/iocBoot/iocAG33220A-IOC-01/config.xml
  AMINT2L/iocBoot/iocAMINT2L-IOC-01/config.xml
  ASTRIUM/iocBoot/iocASTRIUM-IOC-01/config.xml
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/config.xml
  CP2800/iocBoot/iocCP2800-IOC-01/config.xml
  DETADC/iocBoot/iocDETADC-IOC-01/config.xml
  EDTIC/iocBoot/iocEDTIC-IOC-01/config.xml
  EGXCOLIM/iocBoot/iocEGXCOLIM-IOC-01/config.xml
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/config.xml
  FINS/iocBoot/iocFINS-IOC-01/config.xml
  FLIPPRPS/iocBoot/iocFLIPPRPS-IOC-01/config.xml
  FMR/iocBoot/iocFMR-IOC-01/config.xml
  FZJDDFCH/iocBoot/iocFZJDDFCH-IOC-01/config.xml
  GALIL/iocBoot/iocGALIL-IOC-01/config.xml
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/config.xml
  HLG/iocBoot/iocHLG-IOC-01/config.xml
  HVCAEN/iocBoot/iocHVCAEN-IOC-01/config.xml
  HVCAEN/iocBoot/iocHVCAENSIM-IOC-01/config.xml
  ISISDAE/iocBoot/iocISISDAE-IOC-01/config.xml
  KEYLKG/iocBoot/iocKEYLKG-IOC-01/config.xml
  LINMOT/iocBoot/iocLINMOT-IOC-01/config.xml
  LKSH336/iocBoot/iocLKSH336-IOC-01/config.xml
  MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml
  MEZFLIPR/iocBoot/iocMEZFLIPR-IOC-01/config.xml
  MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-01/config.xml
  MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/config.xml
  MUONJAWS/iocBoot/iocMUONJAWS-IOC-01/config.xml
  NANODAC/iocBoot/iocNANODAC-IOC-01/config.xml
  NGPSPSU/iocBoot/iocNGPSPSU-IOC-01/config.xml
  OERCONE/iocBoot/iocOERCONE-IOC-01/config.xml
  PIMOT/iocBoot/iocPIMOT-IOC-01/config.xml
  PT2025/iocBoot/iocPT2025-IOC-01/config.xml
  SAMPOS/iocBoot/iocSAMPOS/config.xml
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/config.xml
  SDTEST/iocBoot/iocSDTEST-IOC-01/config.xml
  SKFMB350/iocBoot/iocSKFMB350-IOC-01/config.xml
  SM300/iocBoot/iocSM300-IOC-01/config.xml
  TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/config.xml
  TRITON/iocBoot/iocTRITON-IOC-01/config.xml
  TWINCAT/iocBoot/iocTWINCAT-IOC-01/config.xml
Labels: size/L

#598 Rework HLX503 as a result of talking to cryogenics
  HLX503/HLX503-IOC-01App/src/build.mak
  HLX503/configure/RELEASE
  HLX503/iocBoot/iocHLX503-IOC-01/config.xml
  HLX503/iocBoot/iocHLX503-IOC-01/st-common.cmd
  HLX503/iocBoot/iocHLX503-IOC-01/st-itc.cmd
Labels: size/L

#606 Adjust library order
  HLX503/HLX503-IOC-01App/src/build.mak
Labels: size/XS

#608 Ticket5729: Add homing mode to config xml
  MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml
Labels: size/S

#610 fix missing xml tag for hlx503
  HLX503/iocBoot/iocHLX503-IOC-01/config.xml
Labels: size/S
