Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2021-08, with the labels that each got.

#625 Added 9000 series danfysik support
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_9X00_status.db
  DFKPS/DFKPS-IOC-01App/Db/Makefile
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-9X00.cmd
Labels: size/L

#627 Update EPICS EUROTHRM SENSOR record to include mV metric
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Labels: size/XS

#628 removing RKNPS ioc
  Makefile
  RKNPS/Makefile
  RKNPS/RKNPS-IOC-01App/Db/DFKPS_RIKEN.db
  RKNPS/RKNPS-IOC-01App/Db/DFKPS_RIKEN_STATUS.db
  RKNPS/RKNPS-IOC-01App/Db/DFKPS_RIKEN_STATUS_ERRORS.substitutions
  RKNPS/RKNPS-IOC-01App/Db/Makefile
  RKNPS/RKNPS-IOC-01App/Db/riken_changeover.db
  RKNPS/RKNPS-IOC-01App/Db/riken_daqmx.db
  RKNPS/RKNPS-IOC-01App/Db/riken_port_changeover_psus.substitutions
  RKNPS/RKNPS-IOC-01App/Db/riken_port_monitor.substitutions
  RKNPS/RKNPS-IOC-01App/Db/riken_port_monitor.template
  RKNPS/RKNPS-IOC-01App/Db/riken_psu_banner.db
  RKNPS/RKNPS-IOC-01App/Db/riken_psus.template
  RKNPS/RKNPS-IOC-01App/Db/riken_rb2_mode_changeover_psus.substitutions
  RKNPS/RKNPS-IOC-01App/Makefile
  RKNPS/RKNPS-IOC-01App/protocol/Makefile
  RKNPS/RKNPS-IOC-01App/src/Makefile
  RKNPS/RKNPS-IOC-01App/src/RKNPS-IOC-01Main.cpp
  RKNPS/RKNPS-IOC-01App/src/build.mak
  RKNPS/RKNPS-IOC-01App/src/coord.dbd
  RKNPS/RKNPS-IOC-01App/src/riken_changeover.st
  RKNPS/RKNPS-IOC-01App/src/seqPVmacros.h
  RKNPS/configure/CONFIG
  RKNPS/configure/CONFIG_SITE
  RKNPS/configure/Makefile
  RKNPS/configure/RELEASE
  RKNPS/configure/RULES
  RKNPS/configure/RULES.ioc
  RKNPS/configure/RULES_DIRS
  RKNPS/configure/RULES_TOP
  RKNPS/iocBoot/Makefile
  RKNPS/iocBoot/iocRKNPS-IOC-01/Makefile
  RKNPS/iocBoot/iocRKNPS-IOC-01/config.xml
  RKNPS/iocBoot/iocRKNPS-IOC-01/st-daq.cmd
  RKNPS/iocBoot/iocRKNPS-IOC-01/st-psu-chain.cmd
  RKNPS/iocBoot/iocRKNPS-IOC-01/st-psu.cmd
  RKNPS/iocBoot/iocRKNPS-IOC-01/st.cmd
Labels: size/XXL

#631 adding units to slew pvs
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_slew.db
Labels: size/XS
