Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-05, with the labels that each got.

#685 added hasdefault=no to both troublesome IOCs
  DG645/iocBoot/iocDG645-IOC-01/config.xml
  KHLY6517/iocBoot/iocKHLY6517-IOC-01/config.xml
Labels: size/XS

#633 Ticket 5238: Add a PV for storing the perspectives to show
  INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
Labels: size/S

#605 Ticket6240 3he fridge cryo logic
  HLX503/HLX503-IOC-01App/src/build.mak
  HLX503/iocBoot/iocHLX503-IOC-01/config.xml
  HLX503/iocBoot/iocHLX503-IOC-01/st-common.cmd
Labels: size/M

#686 Add webcam ioc
  Makefile
  WEBCAM/Makefile
  WEBCAM/WEBCAM-IOC-01App/Db/Makefile
  WEBCAM/WEBCAM-IOC-01App/Makefile
  WEBCAM/WEBCAM-IOC-01App/protocol/Makefile
  WEBCAM/WEBCAM-IOC-01App/src/Makefile
  WEBCAM/WEBCAM-IOC-01App/src/WEBCAM-IOC-01Main.cpp
  WEBCAM/WEBCAM-IOC-01App/src/build.mak
  WEBCAM/configure/CONFIG
  WEBCAM/configure/CONFIG_SITE
  WEBCAM/configure/Makefile
  WEBCAM/configure/RELEASE
  WEBCAM/configure/RULES
  WEBCAM/configure/RULES.ioc
  WEBCAM/configure/RULES_DIRS
  WEBCAM/configure/RULES_TOP
  WEBCAM/iocBoot/Makefile
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/Makefile
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/config.xml
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/st-common.cmd
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/st.cmd
Labels: size/L

#687 Configure webcam
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/WEBCAM_01_settings.req
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/config.xml
  WEBCAM/iocBoot/iocWEBCAM-IOC-01/st-common.cmd
Labels: size/M

#688 Field test fixes
  HLX503/iocBoot/iocHLX503-IOC-01/config.xml
  HLX503/iocBoot/iocHLX503-IOC-01/st-common.cmd
Labels: size/M
