Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-03, with the labels that each got.

#674 Add macro for liveview max elements
  ISISDAE/iocBoot/iocISISDAE-IOC-01/config.xml
  ISISDAE/iocBoot/iocISISDAE-IOC-01/liveview.cmd
Labels: size/XS

#675 EUROTHERM Extend Number of channels to 10
  EUROTHRM/README.md
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/config.xml
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-timing.cmd
Labels: size/M

#646 Added IOC for DG645
  .gitignore
  DG645/DG645-IOC-01App/Db/Makefile
  DG645/DG645-IOC-01App/Makefile
  DG645/DG645-IOC-01App/src/DG645-IOC-01Main.cpp
  DG645/DG645-IOC-01App/src/Makefile
  DG645/DG645-IOC-01App/src/build.mak
  DG645/Makefile
  DG645/configure/CONFIG
  DG645/configure/CONFIG_SITE
  DG645/configure/Makefile
  DG645/configure/RELEASE
  DG645/configure/RULES
  DG645/configure/RULES.ioc
  DG645/configure/RULES_DIRS
  DG645/configure/RULES_TOP
  DG645/iocBoot/Makefile
  DG645/iocBoot/iocDG645-IOC-01/Makefile
  DG645/iocBoot/iocDG645-IOC-01/auto_settings.req
  DG645/iocBoot/iocDG645-IOC-01/config.xml
  DG645/iocBoot/iocDG645-IOC-01/dgconfigMenu.req
  DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
  DG645/iocBoot/iocDG645-IOC-01/st.cmd
  Makefile
Labels: size/L

#676 TEKAFG3XXX: Add macro for IP address
  TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/config.xml
  TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st-common.cmd
Labels: size/XS

#678 Add macros for CCD100 mk3 support
  CCD100/CCD100-IOC-01App/Db/CCD100.db
  CCD100/iocBoot/iocCCD100-IOC-01/config.xml
  CCD100/iocBoot/iocCCD100-IOC-01/st-common.cmd
Labels: size/M
