Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-04, with the labels that each got.

#679 fixing RVAL propagation for AT_VACUUM.RVAL (tank and guides) - this f…
  FINS/FINS-IOC-01App/Db/sans2d-vac-status.template
Labels: size/S

#667 Ticket 4371 ioc opi for rotating stirrer rack
  Makefile
  ROTSTIRR/Makefile
  ROTSTIRR/ROTSTIRR-IOC-01App/Db/Makefile
  ROTSTIRR/ROTSTIRR-IOC-01App/Makefile
  ROTSTIRR/ROTSTIRR-IOC-01App/src/Makefile
  ROTSTIRR/ROTSTIRR-IOC-01App/src/ROTSTIRR-IOC-01Main.cpp
  ROTSTIRR/ROTSTIRR-IOC-01App/src/build.mak
  ROTSTIRR/configure/CONFIG
  ROTSTIRR/configure/CONFIG_SITE
  ROTSTIRR/configure/Makefile
  ROTSTIRR/configure/RELEASE
  ROTSTIRR/configure/RULES
  ROTSTIRR/configure/RULES.ioc
  ROTSTIRR/configure/RULES_DIRS
  ROTSTIRR/configure/RULES_TOP
  ROTSTIRR/example_config/Default.txt
  ROTSTIRR/iocBoot/Makefile
  ROTSTIRR/iocBoot/iocROTSTIRR-IOC-01/Makefile
  ROTSTIRR/iocBoot/iocROTSTIRR-IOC-01/config.xml
  ROTSTIRR/iocBoot/iocROTSTIRR-IOC-01/st-common.cmd
  ROTSTIRR/iocBoot/iocROTSTIRR-IOC-01/st.cmd
Labels: size/L

#682 remove BKHOFF IOC for IMAT stage
  BKHOFF/BKHOFF-IOC-01App/Db/IMAT.substitutions
  BKHOFF/BKHOFF-IOC-01App/Db/Makefile
  BKHOFF/BKHOFF-IOC-01App/Makefile
  BKHOFF/BKHOFF-IOC-01App/src/BKHOFF-IOC-01Main.cpp
  BKHOFF/BKHOFF-IOC-01App/src/Makefile
  BKHOFF/BKHOFF-IOC-01App/src/build.mak
  BKHOFF/BKHOFF-IOC-02App/Db/Makefile
  BKHOFF/BKHOFF-IOC-02App/Makefile
  BKHOFF/BKHOFF-IOC-02App/src/BKHOFF-IOC-02Main.cpp
  BKHOFF/BKHOFF-IOC-02App/src/Makefile
  BKHOFF/BKHOFF-IOC-02App/src/build.mak
  BKHOFF/Makefile
  BKHOFF/configure/CONFIG
  BKHOFF/configure/CONFIG_SITE
  BKHOFF/configure/Makefile
  BKHOFF/configure/RELEASE
  BKHOFF/configure/RULES
  BKHOFF/configure/RULES.ioc
  BKHOFF/configure/RULES_DIRS
  BKHOFF/configure/RULES_TOP
  BKHOFF/iocBoot/Makefile
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/BKHOFF_01_positions.req
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/BKHOFF_01_settings.req
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/Makefile
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/config.xml
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/motor_extras_from_config.cmd
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/motorsim.cmd
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/st-common.cmd
  BKHOFF/iocBoot/iocBKHOFF-IOC-01/st.cmd
  BKHOFF/iocBoot/iocBKHOFF-IOC-02/Makefile
  BKHOFF/iocBoot/iocBKHOFF-IOC-02/config.xml
  BKHOFF/iocBoot/iocBKHOFF-IOC-02/st.cmd
  Makefile
Labels: size/XL
