Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-09, with the labels that each got.

#721 Add motionsetpoints into CONFIGURE/RELEASE for TC
  TC/TC-IOC-01App/src/build.mak
  TC/configure/RELEASE
Labels: size/XS

#724 Ticket4318
  JSCO4180/JSCO4180-IOC-02App/Db/Makefile
  JSCO4180/JSCO4180-IOC-02App/Makefile
  JSCO4180/JSCO4180-IOC-02App/src/JSCO4180-IOC-02Main.cpp
  JSCO4180/JSCO4180-IOC-02App/src/Makefile
  JSCO4180/JSCO4180-IOC-03App/Db/Makefile
  JSCO4180/JSCO4180-IOC-03App/Makefile
  JSCO4180/JSCO4180-IOC-03App/src/JSCO4180-IOC-03Main.cpp
  JSCO4180/JSCO4180-IOC-03App/src/Makefile
  JSCO4180/iocBoot/iocJSCO4180-IOC-02/Makefile
  JSCO4180/iocBoot/iocJSCO4180-IOC-02/config.xml
  JSCO4180/iocBoot/iocJSCO4180-IOC-02/st.cmd
  JSCO4180/iocBoot/iocJSCO4180-IOC-03/Makefile
  JSCO4180/iocBoot/iocJSCO4180-IOC-03/config.xml
  JSCO4180/iocBoot/iocJSCO4180-IOC-03/st.cmd
Labels: size/L

#714 Ticket7283
  TC/TC-IOC-01App/Db/axis_monitors.db
Labels: size/S

#728 Update level/pressure/temp macro patterns
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
Labels: size/S

#727 Ticket 7343
  LKSH336/LKSH336-IOC-01App/Db/lakeshore336.substitutions
Labels: size/S

#732 Add instrona to makefile
  Makefile
Labels: size/XS

#726 TEKAFG3XXX: Remove duplicate dbload, add SCAN macro
  TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st-common.cmd
Labels: size/S

#723 Implement VTI SPC Macros
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-common.cmd
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-temp-spc.cmd
Labels: size/M

#705 Added example settings for zoom FINS for system tests
  FINS/exampleSettings/ZOOM_vacuum/FINS_01.cmd
Labels: size/XS

#734 Ticket7366
  .gitignore
  DG645/DG645-IOC-02App/Db/Makefile
  DG645/DG645-IOC-02App/Makefile
  DG645/DG645-IOC-02App/src/DG645-IOC-02Main.cpp
  DG645/DG645-IOC-02App/src/Makefile
  DG645/DG645-IOC-03App/Db/Makefile
  DG645/DG645-IOC-03App/Makefile
  DG645/DG645-IOC-03App/src/DG645-IOC-03Main.cpp
  DG645/DG645-IOC-03App/src/Makefile
  DG645/iocBoot/iocDG645-IOC-02/Makefile
  DG645/iocBoot/iocDG645-IOC-02/config.xml
  DG645/iocBoot/iocDG645-IOC-02/st.cmd
  DG645/iocBoot/iocDG645-IOC-03/Makefile
  DG645/iocBoot/iocDG645-IOC-03/config.xml
  DG645/iocBoot/iocDG645-IOC-03/st.cmd
Labels: size/L
