Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-08, with the labels that each got.

#708 Tc get velo at startup
  TC/TC-IOC-01App/Db/enabled_monitor.db
Labels: size/XS

#699 Add basic transtechnik PSU ioc
  Makefile
  TRANTECH/Makefile
  TRANTECH/TRANTECH-IOC-01App/Db/Makefile
  TRANTECH/TRANTECH-IOC-01App/Makefile
  TRANTECH/TRANTECH-IOC-01App/src/Makefile
  TRANTECH/TRANTECH-IOC-01App/src/TRANTECH-IOC-01Main.cpp
  TRANTECH/TRANTECH-IOC-01App/src/build.mak
  TRANTECH/TRANTECH-IOC-02App/Db/Makefile
  TRANTECH/TRANTECH-IOC-02App/Makefile
  TRANTECH/TRANTECH-IOC-02App/src/Makefile
  TRANTECH/TRANTECH-IOC-02App/src/TRANTECH-IOC-02Main.cpp
  TRANTECH/configure/CONFIG
  TRANTECH/configure/CONFIG_SITE
  TRANTECH/configure/Makefile
  TRANTECH/configure/RELEASE
  TRANTECH/configure/RULES
  TRANTECH/configure/RULES.ioc
  TRANTECH/configure/RULES_DIRS
  TRANTECH/configure/RULES_TOP
  TRANTECH/iocBoot/Makefile
  TRANTECH/iocBoot/iocTRANTECH-IOC-01/Makefile
  TRANTECH/iocBoot/iocTRANTECH-IOC-01/config.xml
  TRANTECH/iocBoot/iocTRANTECH-IOC-01/st-common.cmd
  TRANTECH/iocBoot/iocTRANTECH-IOC-01/st.cmd
  TRANTECH/iocBoot/iocTRANTECH-IOC-02/Makefile
  TRANTECH/iocBoot/iocTRANTECH-IOC-02/config.xml
  TRANTECH/iocBoot/iocTRANTECH-IOC-02/st.cmd
Labels: size/XL

#712 TRANTECH: move library for static linux link
  TRANTECH/TRANTECH-IOC-01App/src/build.mak
Labels: size/XS

#710 Ticket7253 tjmper phase 1
  Makefile
  TJMPER/Makefile
  TJMPER/TJMPER-IOC-01App/Db/Makefile
  TJMPER/TJMPER-IOC-01App/Db/tjmper.substitutions
  TJMPER/TJMPER-IOC-01App/Makefile
  TJMPER/TJMPER-IOC-01App/src/Makefile
  TJMPER/TJMPER-IOC-01App/src/TJMPER-IOC-01Main.cpp
  TJMPER/TJMPER-IOC-01App/src/build.mak
  TJMPER/configure/CONFIG
  TJMPER/configure/CONFIG_SITE
  TJMPER/configure/Makefile
  TJMPER/configure/RELEASE
  TJMPER/configure/RULES
  TJMPER/configure/RULES.ioc
  TJMPER/configure/RULES_DIRS
  TJMPER/configure/RULES_TOP
  TJMPER/iocBoot/Makefile
  TJMPER/iocBoot/iocTJMPER-IOC-01/Makefile
  TJMPER/iocBoot/iocTJMPER-IOC-01/config.xml
  TJMPER/iocBoot/iocTJMPER-IOC-01/st-common.cmd
  TJMPER/iocBoot/iocTJMPER-IOC-01/st.cmd
Labels: size/L

#713 rename enabled_monitor.db to axis_monitors.db
  TC/TC-IOC-01App/Db/Makefile
  TC/TC-IOC-01App/Db/axis_monitors.db
  TC/iocBoot/iocTC-IOC-01/st-common.lua
Labels: size/XS

#716 Added 'hasDefault' to config.xml to fix iocstartups warnings.
  B17TMAG/iocBoot/iocB17TMAG-IOC-01/config.xml
  TJMPER/iocBoot/iocTJMPER-IOC-01/config.xml
Labels: size/XS

#603 Ticket5993 setup correctly
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd
Labels: size/M

#715 Added script path macro to the Background Script IOC.
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/config.xml
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/dllPath.bat
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/runIOC.bat
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-02/dllPath.bat
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-02/runIOC.bat
  BGRSCRPT/settings/bgrscrpt_script.py
Labels: size/M

#717 Ticket7292 Removed seqPVmacros header duplication.
  FERMCHOP/FERMCHOP-IOC-01App/src/error_logger.st
  FERMCHOP/FERMCHOP-IOC-01App/src/keep_sp_and_rbv_in_sync.st
  FERMCHOP/FERMCHOP-IOC-01App/src/seqPVmacros.h
  HIFIMAGS/HIFIMAGS-IOC-01App/src/hifimagsys.st
  HIFIMAGS/HIFIMAGS-IOC-01App/src/seqPVmacros.h
  INHIBITR/INHIBITR-IOC-01App/src/inhibitor.st
  INHIBITR/INHIBITR-IOC-01App/src/seqPVmacros.h
  IPS/IPS-IOC-01App/src/cryomagnet.st
  IPS/IPS-IOC-01App/src/seqPVmacros.h
Labels: size/XL

#719 Refactor to allow other devices to be accessed
  SCHNDR/SCHNDR-IOC-01App/Db/GEMGateValve.db
  SCHNDR/SCHNDR-IOC-01App/Db/Makefile
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/README.md
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/config.xml
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/devices/GEMGateValve.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/devices/missing.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/devices/nodevice.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/st-ASCII.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/st-RTU.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/st-TCP.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/st-common.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/st.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-02/st.cmd
Labels: size/L

#711 Ticket7261 lksh336 4 loops
  LKSH336/LKSH336-IOC-01App/Db/lakeshore336.substitutions
Labels: size/S
