Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-11, with the labels that each got.

#745 Ticket7400
  KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
Labels: size/XS

#731 Ticket7350
  Makefile
  TJMPAP/Makefile
  TJMPAP/TJMPAP-IOC-01App/Db/Makefile
  TJMPAP/TJMPAP-IOC-01App/Db/tjmpap.substitutions
  TJMPAP/TJMPAP-IOC-01App/Makefile
  TJMPAP/TJMPAP-IOC-01App/src/Makefile
  TJMPAP/TJMPAP-IOC-01App/src/TJMPAP-IOC-01Main.cpp
  TJMPAP/TJMPAP-IOC-01App/src/build.mak
  TJMPAP/configure/CONFIG
  TJMPAP/configure/CONFIG_SITE
  TJMPAP/configure/Makefile
  TJMPAP/configure/RELEASE
  TJMPAP/configure/RULES
  TJMPAP/configure/RULES.ioc
  TJMPAP/configure/RULES_DIRS
  TJMPAP/configure/RULES_TOP
  TJMPAP/iocBoot/Makefile
  TJMPAP/iocBoot/iocTJMPAP-IOC-01/Makefile
  TJMPAP/iocBoot/iocTJMPAP-IOC-01/config.xml
  TJMPAP/iocBoot/iocTJMPAP-IOC-01/st-common.cmd
  TJMPAP/iocBoot/iocTJMPAP-IOC-01/st.cmd
Labels: size/L

#748 Fix static build
  TJMPAP/TJMPAP-IOC-01App/src/build.mak
Labels: size/XS

#749 Added SIM records for zoom vacuum commands.
  FINS/FINS-IOC-01App/Db/zoom-vacuum-commands.template
  FINS/FINS-IOC-01App/Db/zoom-vacuum.substitutions
Labels: size/S

#750 Fix dfkps calib file pattern to allow '.'
  DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
Labels: size/XS

#746 Ticket7376
  DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
Labels: size/XS

#747 Ticket6079 Add Aeroflex IOCs
  AEROFLEX/AEROFLEX-IOC-01App/Makefile
  AEROFLEX/AEROFLEX-IOC-01App/src/AEROFLEX-IOC-01Main.cpp
  AEROFLEX/AEROFLEX-IOC-01App/src/Makefile
  AEROFLEX/AEROFLEX-IOC-01App/src/build.mak
  AEROFLEX/AEROFLEX-IOC-02App/Db/Makefile
  AEROFLEX/AEROFLEX-IOC-02App/Makefile
  AEROFLEX/AEROFLEX-IOC-02App/src/AEROFLEX-IOC-02Main.cpp
  AEROFLEX/AEROFLEX-IOC-02App/src/Makefile
  AEROFLEX/AEROFLEX-IOC-03App/Db/Makefile
  AEROFLEX/AEROFLEX-IOC-03App/Makefile
  AEROFLEX/AEROFLEX-IOC-03App/src/AEROFLEX-IOC-03Main.cpp
  AEROFLEX/AEROFLEX-IOC-03App/src/Makefile
  AEROFLEX/Makefile
  AEROFLEX/configure/CONFIG
  AEROFLEX/configure/CONFIG_SITE
  AEROFLEX/configure/Makefile
  AEROFLEX/configure/RELEASE
  AEROFLEX/configure/RULES
  AEROFLEX/configure/RULES.ioc
  AEROFLEX/configure/RULES_DIRS
  AEROFLEX/configure/RULES_TOP
  AEROFLEX/iocBoot/Makefile
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-01/Makefile
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-01/config.xml
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-01/st-2023A.cmd
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-01/st-2030.cmd
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-01/st-common.cmd
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-01/st.cmd
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-02/Makefile
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-02/config.xml
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-02/st.cmd
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-03/Makefile
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-03/config.xml
  AEROFLEX/iocBoot/iocAEROFLEX-IOC-03/st.cmd
  Makefile
Labels: size/XL

#744 Add macro to control jaws autosave SP
  GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-common.cmd
  LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd
Labels: size/XS
