Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-12, with the labels that each got.

#752 Add booster_Type pv
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd
Labels: size/XS

#733 Configure fins timeout
  FINS/FINS-IOC-01App/Db/address-read.template
  FINS/FINS-IOC-01App/Db/he-recovery-auto-manual.template
  FINS/FINS-IOC-01App/Db/he-recovery-dword.template
  FINS/FINS-IOC-01App/Db/he-recovery-header.template
  FINS/FINS-IOC-01App/Db/he-recovery-int.template
  FINS/FINS-IOC-01App/Db/he-recovery-real.template
  FINS/FINS-IOC-01App/Db/he-recovery-valve.template
  FINS/FINS-IOC-01App/Db/he-recovery.substitutions
  FINS/FINS-IOC-01App/Db/imat-plc-attn-main.template
  FINS/FINS-IOC-01App/Db/imat-plc-attn.substitutions
  FINS/FINS-IOC-01App/Db/imat-plc-press.substitutions
  FINS/FINS-IOC-01App/Db/larmor-air-flow.template
  FINS/FINS-IOC-01App/Db/larmor-air-header.template
  FINS/FINS-IOC-01App/Db/larmor-air-valve.template
  FINS/FINS-IOC-01App/Db/larmor-air.substitutions
  FINS/FINS-IOC-01App/Db/press-main.template
  FINS/FINS-IOC-01App/Db/sans2d-general-status.template
  FINS/FINS-IOC-01App/Db/sans2d-pressure-read.template
  FINS/FINS-IOC-01App/Db/sans2d-pump-add.template
  FINS/FINS-IOC-01App/Db/sans2d-pump-basics.template
  FINS/FINS-IOC-01App/Db/sans2d-pump-valve-status.template
  FINS/FINS-IOC-01App/Db/sans2d-vac-status.template
  FINS/FINS-IOC-01App/Db/sans2d-vacuum.substitutions
  FINS/FINS-IOC-01App/Db/wish-vacuum.substitutions
  FINS/FINS-IOC-01App/Db/wish-vacuum.template
  FINS/FINS-IOC-01App/Db/write-bit.template
  FINS/FINS-IOC-01App/Db/zoom-vacuum-base.template
  FINS/FINS-IOC-01App/Db/zoom-vacuum-commands.template
  FINS/FINS-IOC-01App/Db/zoom-vacuum-main-error.template
  FINS/FINS-IOC-01App/Db/zoom-vacuum-main.template
  FINS/FINS-IOC-01App/Db/zoom-vacuum.substitutions
  FINS/exampleSettings/HELIUM_RECOVERY/FINS_01.cmd
  FINS/exampleSettings/LARMOR_bench/FINS_01.cmd
  FINS/exampleSettings/SANS2D_vacuum/FINS_01.cmd
  FINS/iocBoot/iocFINS-IOC-01/config.xml
Labels: size/L

#755 Ticket7241 riken plc configuration
  .gitignore
  SCHNDR/SCHNDR-IOC-01App/Db/Makefile
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE.substitutions
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_BeamBlocker_Information.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Common_Objects_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Header.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Integer.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Kicker_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_PIV_Interlock_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_RBox_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Solenoid_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_TEMPMON.substitutions
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Vacuum_Pump_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Vacuum_Valve_Interlock_Status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Vacuum_Valve_Open.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_float.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_other_objects_status.template
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_vacuum_valve_status.template
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/devices/RIKENFE.cmd
  SCHNDR/iocBoot/iocSCHNDR-IOC-01/st-TCP.cmd
Labels: size/XXL

#757 Mercury IPS mods
  IPS/IPS-IOC-01App/Db/ips.db
  IPS/IPS-IOC-01App/src/cryomagnet.st
Labels: size/XS

#754 Create PVs needed for custom magnet OPI for RIKENFE
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE.substitutions
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Kicker_Summary.template
  TECHNIX/iocBoot/iocTECHNIX-IOC-01/config.xml
  TECHNIX/iocBoot/iocTECHNIX-IOC-01/st-common.cmd
  TRANTECH/iocBoot/iocTRANTECH-IOC-01/config.xml
  TRANTECH/iocBoot/iocTRANTECH-IOC-01/st-common.cmd
Labels: size/L

#758 Ticket6100
  SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-01/config.xml
Labels: size/XS

#760 Test adsdriver
  TC/TC-IOC-01App/Db/Makefile
  TC/TC-IOC-01App/Db/axis_monitors.db
  TC/TC-IOC-01App/Db/single_axis_tc.db
  TC/TC-IOC-01App/src/build.mak
  TC/configure/RELEASE
  TC/iocBoot/iocTC-IOC-01/TC_01_settings.req
  TC/iocBoot/iocTC-IOC-01/config.xml
  TC/iocBoot/iocTC-IOC-01/st-common.cmd
  TC/iocBoot/iocTC-IOC-01/st-common.lua
Labels: size/L

#761 Update single_axis_tc.db
  TC/TC-IOC-01App/Db/single_axis_tc.db
Labels: size/XS
