Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2022-10, with the labels that each got.

#739 add asub to build.mak for TC
  TC/TC-IOC-01App/src/build.mak
Labels: size/XS

#740 add IOCNAME to all motorstatus.db loads
  CONEXAGP/iocBoot/iocCONEXAGP-IOC-01/st-motor.cmd
  GALIL/iocBoot/iocGALIL-IOC-01/galildb.cmd
  GALILMUL/iocBoot/iocGALILMUL-IOC-01/galildb.cmd
  HUBER/iocBoot/iocHUBER-IOC-01/st-motor.cmd
  LINMOT/iocBoot/iocLINMOT-IOC-01/st-motor.cmd
  MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
  NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-motor.cmd
  PIMOT/iocBoot/iocPIMOT-IOC-01/st-common.cmd
  SMC100/iocBoot/iocSMC100-IOC-01/st-motor.cmd
  TC/iocBoot/iocTC-IOC-01/st-common.lua
Labels: size/S

#741 Add Tektronix Osc IOC and Additional Background Script IOC
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-03/config.xml
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-03/dllPath.bat
  BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-03/runIOC.bat
  Makefile
  TEKOSC/Makefile
  TEKOSC/TEKOSC-IOC-01App/Db/Makefile
  TEKOSC/TEKOSC-IOC-01App/Makefile
  TEKOSC/TEKOSC-IOC-01App/src/Makefile
  TEKOSC/TEKOSC-IOC-01App/src/TEKOSC-IOC-01Main.cpp
  TEKOSC/TEKOSC-IOC-01App/src/build.mak
  TEKOSC/configure/CONFIG
  TEKOSC/configure/CONFIG_SITE
  TEKOSC/configure/Makefile
  TEKOSC/configure/RELEASE
  TEKOSC/configure/RULES
  TEKOSC/configure/RULES.ioc
  TEKOSC/configure/RULES_DIRS
  TEKOSC/configure/RULES_TOP
  TEKOSC/iocBoot/Makefile
  TEKOSC/iocBoot/iocTEKOSC-IOC-01/Makefile
  TEKOSC/iocBoot/iocTEKOSC-IOC-01/config.xml
  TEKOSC/iocBoot/iocTEKOSC-IOC-01/st-common.cmd
  TEKOSC/iocBoot/iocTEKOSC-IOC-01/st.cmd
Labels: size/L

#743 Fix macro being wrong for lookup file directory
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-temp-spc.cmd
Labels: size/XS

#742 Allow the DG645 to be controlled via ethernet
  DG645/iocBoot/iocDG645-IOC-01/config.xml
  DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
Labels: size/S
