Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2023-06, with the labels that each got.

#789 update configure/RELEASE to include relevant motor modules for each motor IOC
  CONEXAGP/configure/RELEASE
  GALIL/configure/RELEASE
  GALILMUL/configure/RELEASE
  HUBER/configure/RELEASE
  LINMOT/configure/RELEASE
  MCLEN/configure/RELEASE
  NWPRTXPS/NWPRTXPS-IOC-01App/Db/motor.substitutions
  NWPRTXPS/configure/RELEASE
  PIMOT/configure/RELEASE
  SM300/configure/RELEASE
  SMC100/configure/RELEASE
  TC/configure/RELEASE
Labels: size/L

#793 Make buffer size a multiple of 3 (1000->999)
  KHLY2700/KHLY2700-IOC-01App/Db/keithley2700.db
  KHLY2700/iocBoot/iocKHLY2700-IOC-01/st-common.cmd
Labels: size/XS

#794 Ticket4390 read homing routines as pv
  GALIL/GALIL-IOC-01App/Db/Makefile
  GALIL/GALIL-IOC-01App/Db/galil_homing_routines.substitutions
  GALIL/iocBoot/iocGALIL-IOC-01/galildb.cmd
Labels: size/S
