Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2023-08, with the labels that each got.

#803 Ticket7955
  TC/TC-IOC-01App/Db/single_axis_tc.db
  TC/iocBoot/iocTC-IOC-01/st-common.lua
Labels: size/L

#800 Ticket6042
  DHP30330/DHP30330-IOC-01App/Db/Makefile
  DHP30330/DHP30330-IOC-01App/Makefile
  DHP30330/DHP30330-IOC-01App/src/DHP30330-IOC-01Main.cpp
  DHP30330/DHP30330-IOC-01App/src/Makefile
  DHP30330/DHP30330-IOC-01App/src/build.mak
  DHP30330/Makefile
  DHP30330/configure/CONFIG
  DHP30330/configure/CONFIG_SITE
  DHP30330/configure/Makefile
  DHP30330/configure/RELEASE
  DHP30330/configure/RULES
  DHP30330/configure/RULES.ioc
  DHP30330/configure/RULES_DIRS
  DHP30330/configure/RULES_TOP
  DHP30330/iocBoot/Makefile
  DHP30330/iocBoot/iocDHP30330-IOC-01/Makefile
  DHP30330/iocBoot/iocDHP30330-IOC-01/config.xml
  DHP30330/iocBoot/iocDHP30330-IOC-01/st-common.cmd
  DHP30330/iocBoot/iocDHP30330-IOC-01/st.cmd
  Makefile
Labels: size/L

#781 Ticket6777
  EUROTHRM/EUROTHRM-IOC-01App/Db/Makefile
  EUROTHRM/EUROTHRM-IOC-01App/Db/automaticNeedleValve.db
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/config.xml
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-comms-modbus.cmd
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
Labels: size/L

#804 Ticket7875 add iologik1242 to our ioc
  MOXA12XX/MOXA12XX-IOC-01App/Db/Makefile
  MOXA12XX/MOXA12XX-IOC-01App/Db/moxa_e1242_PVs.substitutions
  MOXA12XX/MOXA12XX-IOC-01App/Db/moxa_e1242_misc.db
  MOXA12XX/MOXA12XX-IOC-01App/Db/moxa_e1242_misc.substitutions
  MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/config.xml
  MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-aliases.cmd
  MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-common.cmd
  MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-e1242.cmd
Labels: size/L

#801 Pass additional macros for restore
  DG645/DG645-IOC-01App/src/build.mak
  DG645/iocBoot/iocDG645-IOC-01/auto_settings.req
  DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
Labels: size/S

#798 Refactor and generalise TPG300 IOC
  TPG300/iocBoot/iocTPG300-IOC-01/config.xml
  TPG300/iocBoot/iocTPG300-IOC-01/st-common.cmd
Labels: size/M
