Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2023-01, with the labels that each got.

#763 Build TC only with twincat on windows
  Makefile
Labels: size/XS

#756 Ticket7058
  SPRLG/iocBoot/iocSPRLG-IOC-01/config.xml
  SPRLG/iocBoot/iocSPRLG-IOC-01/st-common.cmd
Labels: size/M

#753 instron
  INSTRONA/iocBoot/iocINSTRONA-IOC-01/st.cmd
Labels: size/S

#764 Avoid a file copy race condition
  ASTRIUM/ASTRIUM-IOC-01App/src/Makefile
  ASTRIUM/ASTRIUM-IOC-01App/src/build.mak
  HVCAEN/HVCAEN-IOC-01App/src/Makefile
  HVCAEN/HVCAEN-IOC-01App/src/build.mak
  HVCAENA/HVCAENA-IOC-01App/src/Makefile
  HVCAENA/HVCAENA-IOC-01App/src/build.mak
  MK3CHOPR/MK3CHOPR-IOC-01App/src/Makefile
  MK3CHOPR/MK3CHOPR-IOC-01App/src/build.mak
Labels: size/S

#767 Add IOCNAME macro.
  GALIL/GALIL-IOC-01App/Db/galil_motor_extras.substitutions
Labels: size/S

#736 Changes to RIKEN SCHNEIDER template to add summary PVs for OPI
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE.substitutions
  SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Pumpset_Summary.template
Labels: size/M

#766 Ticket7543 sandals gate valve
  FINS/FINS-IOC-01App/Db/Makefile
  FINS/FINS-IOC-01App/Db/sandals-base.template
  FINS/FINS-IOC-01App/Db/sandals-gate-valve-single.template
  FINS/FINS-IOC-01App/Db/sandals-gate-valve.substitutions
  FINS/exampleSettings/SANDALS_gate_valve/FINS_01.cmd
Labels: size/L

#768 Add Keithley 2000
  KHLY2000/KHLY2000-IOC-01App/Makefile
  KHLY2000/KHLY2000-IOC-01App/src/KHLY2000-IOC-01Main.cpp
  KHLY2000/KHLY2000-IOC-01App/src/Makefile
  KHLY2000/KHLY2000-IOC-01App/src/build.mak
  KHLY2000/KHLY2000-IOC-02App/Makefile
  KHLY2000/KHLY2000-IOC-02App/src/KHLY2000-IOC-02Main.cpp
  KHLY2000/KHLY2000-IOC-02App/src/Makefile
  KHLY2000/Makefile
  KHLY2000/configure/CONFIG
  KHLY2000/configure/CONFIG_SITE
  KHLY2000/configure/Makefile
  KHLY2000/configure/RELEASE
  KHLY2000/configure/RULES
  KHLY2000/configure/RULES.ioc
  KHLY2000/configure/RULES_DIRS
  KHLY2000/configure/RULES_TOP
  KHLY2000/iocBoot/Makefile
  KHLY2000/iocBoot/iocKHLY2000-IOC-01/Makefile
  KHLY2000/iocBoot/iocKHLY2000-IOC-01/config.xml
  KHLY2000/iocBoot/iocKHLY2000-IOC-01/st-common.cmd
  KHLY2000/iocBoot/iocKHLY2000-IOC-01/st.cmd
  KHLY2000/iocBoot/iocKHLY2000-IOC-02/Makefile
  KHLY2000/iocBoot/iocKHLY2000-IOC-02/config.xml
  KHLY2000/iocBoot/iocKHLY2000-IOC-02/st.cmd
  Makefile
Labels: size/L

#769 Fix dbcheck errors
  FINS/FINS-IOC-01App/Db/sandals-base.template
Labels: size/XS

#770 Update from larmor pc
  DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/Makefile
  DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/NSV.db
  DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/NSV1.db
  DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/NSV1T.substitutions
  DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/NSV_read_only.db
  DELFTDCMAG/DELFTDCMAG-IOC-01App/protocol/DELFTDCMAG_nv.xml
  DELFTDCMAG/iocBoot/iocDELFTDCMAG-IOC-01/st.cmd
Labels: size/XL
