Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2023-09, with the labels that each got.

#805 Ticket7820 add ioc pre4500
  Makefile
  PRE4500/Makefile
  PRE4500/PRE4500-IOC-01App/Db/Makefile
  PRE4500/PRE4500-IOC-01App/Db/PRE4500.db
  PRE4500/PRE4500-IOC-01App/Makefile
  PRE4500/PRE4500-IOC-01App/src/Makefile
  PRE4500/PRE4500-IOC-01App/src/PRE4500-IOC-01Main.cpp
  PRE4500/PRE4500-IOC-01App/src/build.mak
  PRE4500/PRE4500-IOC-02App/Db/Makefile
  PRE4500/PRE4500-IOC-02App/Makefile
  PRE4500/PRE4500-IOC-02App/src/Makefile
  PRE4500/PRE4500-IOC-02App/src/PRE4500-IOC-02Main.cpp
  PRE4500/PRE4500-IOC-03App/Db/Makefile
  PRE4500/PRE4500-IOC-03App/Makefile
  PRE4500/PRE4500-IOC-03App/src/Makefile
  PRE4500/PRE4500-IOC-03App/src/PRE4500-IOC-03Main.cpp
  PRE4500/PRE4500-IOC-04App/Db/Makefile
  PRE4500/PRE4500-IOC-04App/Makefile
  PRE4500/PRE4500-IOC-04App/src/Makefile
  PRE4500/PRE4500-IOC-04App/src/PRE4500-IOC-04Main.cpp
  PRE4500/PRE4500-IOC-05App/Db/Makefile
  PRE4500/PRE4500-IOC-05App/Makefile
  PRE4500/PRE4500-IOC-05App/src/Makefile
  PRE4500/PRE4500-IOC-05App/src/PRE4500-IOC-05Main.cpp
  PRE4500/configure/CONFIG
  PRE4500/configure/CONFIG_SITE
  PRE4500/configure/Makefile
  PRE4500/configure/RELEASE
  PRE4500/configure/RULES
  PRE4500/configure/RULES.ioc
  PRE4500/configure/RULES_DIRS
  PRE4500/configure/RULES_TOP
  PRE4500/iocBoot/Makefile
  PRE4500/iocBoot/iocPRE4500-IOC-01/Makefile
  PRE4500/iocBoot/iocPRE4500-IOC-01/config.xml
  PRE4500/iocBoot/iocPRE4500-IOC-01/st-common.cmd
  PRE4500/iocBoot/iocPRE4500-IOC-01/st-comms-modbus.cmd
  PRE4500/iocBoot/iocPRE4500-IOC-01/st.cmd
  PRE4500/iocBoot/iocPRE4500-IOC-02/Makefile
  PRE4500/iocBoot/iocPRE4500-IOC-02/config.xml
  PRE4500/iocBoot/iocPRE4500-IOC-02/st.cmd
  PRE4500/iocBoot/iocPRE4500-IOC-03/Makefile
  PRE4500/iocBoot/iocPRE4500-IOC-03/config.xml
  PRE4500/iocBoot/iocPRE4500-IOC-03/st.cmd
  PRE4500/iocBoot/iocPRE4500-IOC-04/Makefile
  PRE4500/iocBoot/iocPRE4500-IOC-04/config.xml
  PRE4500/iocBoot/iocPRE4500-IOC-04/st.cmd
  PRE4500/iocBoot/iocPRE4500-IOC-05/Makefile
  PRE4500/iocBoot/iocPRE4500-IOC-05/config.xml
  PRE4500/iocBoot/iocPRE4500-IOC-05/st.cmd
Labels: size/XL

#806 Update st-common.cmd
  TPG300/iocBoot/iocTPG300-IOC-01/st-common.cmd
Labels: size/XS

#808 Inter additions
  TC/TC-IOC-01App/Db/axis_monitors.db
  TC/iocBoot/iocTC-IOC-01/st-common.lua
Labels: size/S

#810 Update config.xml
  CATFLWR/iocBoot/iocCATFLWR-IOC-01/config.xml
Labels: size/XS

#809 Update config.xml
  PRE4500/iocBoot/iocPRE4500-IOC-01/config.xml
Labels: size/XS

#811 Ticket8000
  FINS/FINS-IOC-01App/Db/sandals-base.template
Labels: size/S

#791 Ticket 7005
  CCD100/CCD100-IOC-01App/Db/CCD100.db
  CCD100/iocBoot/iocCCD100-IOC-01/st-common.cmd
Labels: size/S
