Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2023-02, with the labels that each got.

#759 Follows GUI & IOC testing in integration with IBEX.
  KHLY2290/KHLY2290-IOC-01App/Db/Makefile
  KHLY2290/KHLY2290-IOC-01App/Makefile
  KHLY2290/KHLY2290-IOC-01App/protocol/Makefile
  KHLY2290/KHLY2290-IOC-01App/src/KHLY2290-IOC-01Main.cpp
  KHLY2290/KHLY2290-IOC-01App/src/Makefile
  KHLY2290/KHLY2290-IOC-01App/src/build.mak
  KHLY2290/KHLY2290-IOC-02App/Db/Makefile
  KHLY2290/KHLY2290-IOC-02App/Makefile
  KHLY2290/KHLY2290-IOC-02App/protocol/Makefile
  KHLY2290/KHLY2290-IOC-02App/src/KHLY2290-IOC-02Main.cpp
  KHLY2290/KHLY2290-IOC-02App/src/Makefile
  KHLY2290/Makefile
  KHLY2290/configure/CONFIG
  KHLY2290/configure/CONFIG_SITE
  KHLY2290/configure/Makefile
  KHLY2290/configure/RELEASE
  KHLY2290/configure/RULES
  KHLY2290/configure/RULES.ioc
  KHLY2290/configure/RULES_DIRS
  KHLY2290/configure/RULES_TOP
  KHLY2290/iocBoot/Makefile
  KHLY2290/iocBoot/iocKHLY2290-IOC-01/Makefile
  KHLY2290/iocBoot/iocKHLY2290-IOC-01/config.xml
  KHLY2290/iocBoot/iocKHLY2290-IOC-01/st-common.cmd
  KHLY2290/iocBoot/iocKHLY2290-IOC-01/st.cmd
  KHLY2290/iocBoot/iocKHLY2290-IOC-02/Makefile
  KHLY2290/iocBoot/iocKHLY2290-IOC-02/config.xml
  KHLY2290/iocBoot/iocKHLY2290-IOC-02/st-common.cmd
  KHLY2290/iocBoot/iocKHLY2290-IOC-02/st.cmd
  Makefile
Labels: size/XL

#762 Ticket6931 eurotherm output rate controls
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
Labels: size/L

#771 Ticket6891 IPS Statemachine
  IPS/IPS-IOC-01App/Db/ips.db
  IPS/IPS-IOC-01App/src/cryomagnet.st
  IPS/iocBoot/iocIPS-IOC-01/st.cmd
Labels: size/M

#773 Update axis_monitors.db
  TC/TC-IOC-01App/Db/axis_monitors.db
Labels: size/XS

#772 Ticket7561
  SPRLG/iocBoot/iocSPRLG-IOC-01/config.xml
  SPRLG/iocBoot/iocSPRLG-IOC-01/st-common.cmd
  SPRLG/iocBoot/iocSPRLG-IOC-01/st-strain.cmd
  SPRLG/iocBoot/iocSPRLG-IOC-01/st-thermo.cmd
Labels: size/M
