Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2023-05, with the labels that each got.

#784 Eurotherm: Output records cannot be I/O Intr
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Labels: size/XS

#785 Fixed macro having no 'hasDefault' value
  RZBRP100/iocBoot/iocRZBRP100-IOC-01/config.xml
Labels: size/XS

#782 Add more parameter setup, fix potential PCOF issue
  MCLEN/MCLEN-IOC-01App/Db/mclen_motor_extra.db
  MCLEN/MCLEN-IOC-01App/Db/motor.substitutions
  MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml
  MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd
  MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor-init.cmd
  MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
  MCLEN/iocBoot/iocMCLEN-IOC-01/st.cmd
Labels: size/M

#786 Area, speed, and pressure macros
  NIMATRO/NIMATRO-IOC-01App/Db/controls.db
  NIMATRO/iocBoot/iocNIMATRO-IOC-01/config.xml
  NIMATRO/iocBoot/iocNIMATRO-IOC-01/st-common.cmd
Labels: size/S
