Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-06, with the labels that each got.

#834 Ticket6049 add ioc prltherm
  Makefile
  PRLTHERM/Makefile
  PRLTHERM/PRLTHERM-IOC-01App/Db/Makefile
  PRLTHERM/PRLTHERM-IOC-01App/Makefile
  PRLTHERM/PRLTHERM-IOC-01App/src/Makefile
  PRLTHERM/PRLTHERM-IOC-01App/src/PRLTHERM-IOC-01Main.cpp
  PRLTHERM/PRLTHERM-IOC-01App/src/build.mak
  PRLTHERM/configure/CONFIG
  PRLTHERM/configure/CONFIG_SITE
  PRLTHERM/configure/Makefile
  PRLTHERM/configure/RELEASE
  PRLTHERM/configure/RULES
  PRLTHERM/configure/RULES.ioc
  PRLTHERM/configure/RULES_DIRS
  PRLTHERM/configure/RULES_TOP
  PRLTHERM/iocBoot/Makefile
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/Makefile
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/config.xml
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/st-daq.cmd
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/st.cmd
Labels: size/L

#860 fix caen macros
  CAENV895/iocBoot/iocCAENV895-IOC-01/config.xml
  CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd
Labels: size/M

#858 Ticket8341_set_alarm_severity_based_on_macro
  TPG300/iocBoot/iocTPG300-IOC-01/config.xml
  TPG300/iocBoot/iocTPG300-IOC-01/st-common.cmd
Labels: size/XS

#862 Corrected macro name in DAQMX startup file, changed default CJC source
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/config.xml
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/st-daq.cmd
Labels: size/XS

#853 Support daisy chaining pumps
  ALDN1000/iocBoot/iocALDN1000-IOC-01/config.xml
  ALDN1000/iocBoot/iocALDN1000-IOC-01/st-common.cmd
Labels: size/M

#863 Add template IOC
  SR400/Makefile
  SR400/SR400-IOC-01App/Makefile
  SR400/SR400-IOC-01App/src/Makefile
  SR400/SR400-IOC-01App/src/SR400-IOC-01Main.cpp
  SR400/SR400-IOC-01App/src/build.mak
  SR400/SR400-IOC-02App/Db/Makefile
  SR400/SR400-IOC-02App/Makefile
  SR400/SR400-IOC-02App/src/Makefile
  SR400/SR400-IOC-02App/src/SR400-IOC-02Main.cpp
  SR400/configure/CONFIG
  SR400/configure/CONFIG_SITE
  SR400/configure/Makefile
  SR400/configure/RELEASE
  SR400/configure/RULES
  SR400/configure/RULES.ioc
  SR400/configure/RULES_DIRS
  SR400/configure/RULES_TOP
  SR400/iocBoot/Makefile
  SR400/iocBoot/iocSR400-IOC-01/Makefile
  SR400/iocBoot/iocSR400-IOC-01/config.xml
  SR400/iocBoot/iocSR400-IOC-01/st-common.cmd
  SR400/iocBoot/iocSR400-IOC-01/st.cmd
  SR400/iocBoot/iocSR400-IOC-02/Makefile
  SR400/iocBoot/iocSR400-IOC-02/config.xml
  SR400/iocBoot/iocSR400-IOC-02/st.cmd
Labels: size/L
