Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-09, with the labels that each got.

#876 Linmot fixes for SXD
  LINMOT/iocBoot/iocLINMOT-IOC-01/config.xml
  LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd
  LINMOT/iocBoot/iocLINMOT-IOC-01/st-motor.cmd
Labels: size/S

#879 Use WA
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_8500_status.db
Labels: size/XS

#878 Fix from hifi-cryomag
  CRYOSMS/CRYOSMS-IOC-03App/Makefile
  CRYOSMS/CRYOSMS-IOC-03App/src/CRYOSMS-IOC-03Main.cpp
  CRYOSMS/CRYOSMS-IOC-03App/src/Makefile
  CRYOSMS/CRYOSMS-IOC-04App/Makefile
  CRYOSMS/CRYOSMS-IOC-04App/src/CRYOSMS-IOC-04Main.cpp
  CRYOSMS/CRYOSMS-IOC-04App/src/Makefile
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml
  CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags.db
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags_magnet.template
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/mainpsu.db
  HIFIMAGS/HIFIMAGS-IOC-01App/Db/switching.db
  HIFIMAGS/HIFIMAGS-IOC-01App/src/hifimagsys.st
  KHLY2700/KHLY2700-IOC-01App/Db/keithley2700_channels.substitutions
Labels: size/M

#877 Ticket6232 ability to edit tpar file within ibex
  MUONTPAR/MUONTPAR-IOC-01App/src/build.mak
  MUONTPAR/configure/RELEASE
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd
Labels: size/S

#880 add 4 more lindy IOCs
  LNDYISW/LNDYISW-IOC-03App/Db/Makefile
  LNDYISW/LNDYISW-IOC-03App/Makefile
  LNDYISW/LNDYISW-IOC-03App/src/LNDYISW-IOC-03Main.cpp
  LNDYISW/LNDYISW-IOC-03App/src/Makefile
  LNDYISW/LNDYISW-IOC-04App/Db/Makefile
  LNDYISW/LNDYISW-IOC-04App/Makefile
  LNDYISW/LNDYISW-IOC-04App/src/LNDYISW-IOC-04Main.cpp
  LNDYISW/LNDYISW-IOC-04App/src/Makefile
  LNDYISW/LNDYISW-IOC-05App/Db/Makefile
  LNDYISW/LNDYISW-IOC-05App/Makefile
  LNDYISW/LNDYISW-IOC-05App/src/LNDYISW-IOC-05Main.cpp
  LNDYISW/LNDYISW-IOC-05App/src/Makefile
  LNDYISW/LNDYISW-IOC-06App/Db/Makefile
  LNDYISW/LNDYISW-IOC-06App/Makefile
  LNDYISW/LNDYISW-IOC-06App/src/LNDYISW-IOC-06Main.cpp
  LNDYISW/LNDYISW-IOC-06App/src/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-03/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-03/config.xml
  LNDYISW/iocBoot/iocLNDYISW-IOC-03/st.cmd
  LNDYISW/iocBoot/iocLNDYISW-IOC-04/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-04/config.xml
  LNDYISW/iocBoot/iocLNDYISW-IOC-04/st.cmd
  LNDYISW/iocBoot/iocLNDYISW-IOC-05/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-05/config.xml
  LNDYISW/iocBoot/iocLNDYISW-IOC-05/st.cmd
  LNDYISW/iocBoot/iocLNDYISW-IOC-06/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-06/config.xml
  LNDYISW/iocBoot/iocLNDYISW-IOC-06/st.cmd
Labels: size/L

#883 Add inst sync
  NCINDG/iocBoot/iocNCINDG-IOC-01/config.xml
  NCINDG/iocBoot/iocNCINDG-IOC-01/st-common.cmd
Labels: size/XS
