Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-07, with the labels that each got.

#866 sum read every 200ms rather than 1ms
  TC/iocBoot/iocTC-IOC-01/st-common.cmd
Labels: size/XS

#868 Added alarm field & default emulator port
  DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
  DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd
Labels: size/XS

#867 add ioc startup stuff for hameg8123 streams, remove old db now in sup…
  HAMEG8123/HAMEG8123-IOC-01App/Db/Makefile
  HAMEG8123/HAMEG8123-IOC-01App/Db/devHameg_8123.db
  HAMEG8123/iocBoot/iocHAMEG8123-IOC-01/st-common.cmd
Labels: size/XL

#869 exit if no NUM_AXES defined
  TC/iocBoot/iocTC-IOC-01/st-common.cmd
Labels: size/S

#871 Fix missing newline
  DDSSTRES/configure/RELEASE
Labels: size/XS

#872 duplicate tekdmm40x0 ioc and make 4 iocs - needed for CHIPIR
  TEKDMM40X0/TEKDMM40X0-IOC-02App/Db/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-02App/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-02App/src/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-02App/src/TEKDMM40X0-IOC-02Main.cpp
  TEKDMM40X0/TEKDMM40X0-IOC-03App/Db/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-03App/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-03App/src/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-03App/src/TEKDMM40X0-IOC-03Main.cpp
  TEKDMM40X0/TEKDMM40X0-IOC-04App/Db/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-04App/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-04App/src/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-04App/src/TEKDMM40X0-IOC-04Main.cpp
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-02/Makefile
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-02/config.xml
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-02/st.cmd
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-03/Makefile
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-03/config.xml
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-03/st.cmd
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-04/Makefile
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-04/config.xml
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-04/st.cmd
Labels: size/L
