Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-11, with the labels that each got.

#889 add current pearl camera settings from NDXPEARL
  GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd
Labels: size/XS

#888 Ticket8400 add ioc group3 hall probe
  G3HALLPR/G3HALLPR-IOC-01App/Makefile
  G3HALLPR/G3HALLPR-IOC-01App/src/G3HALLPR-IOC-01Main.cpp
  G3HALLPR/G3HALLPR-IOC-01App/src/Makefile
  G3HALLPR/G3HALLPR-IOC-01App/src/build.mak
  G3HALLPR/G3HALLPR-IOC-02App/Db/Makefile
  G3HALLPR/G3HALLPR-IOC-02App/Makefile
  G3HALLPR/G3HALLPR-IOC-02App/src/G3HALLPR-IOC-02Main.cpp
  G3HALLPR/G3HALLPR-IOC-02App/src/Makefile
  G3HALLPR/Makefile
  G3HALLPR/configure/CONFIG
  G3HALLPR/configure/CONFIG_SITE
  G3HALLPR/configure/Makefile
  G3HALLPR/configure/RELEASE
  G3HALLPR/configure/RULES
  G3HALLPR/configure/RULES.ioc
  G3HALLPR/configure/RULES_DIRS
  G3HALLPR/configure/RULES_TOP
  G3HALLPR/iocBoot/Makefile
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/Makefile
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/config.xml
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/st-common.cmd
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/st.cmd
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-02/Makefile
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-02/config.xml
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-02/st.cmd
  Makefile
Labels: size/XL

#891 Pulled host out to common macro
  COMMON/HOST.xml
  KSE4980/iocBoot/iocKSE4980-IOC-01/config.xml
  LKSH336/iocBoot/iocLKSH336-IOC-01/config.xml
  MEZFLIPR/iocBoot/iocMEZFLIPR-IOC-01/config.xml
  PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/config.xml
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
Labels: size/S

#890 Ticket6085 add IOC Thorlabs FW102C
  Makefile
  TLFW102C/Makefile
  TLFW102C/TLFW102C-IOC-01App/Makefile
  TLFW102C/TLFW102C-IOC-01App/src/Makefile
  TLFW102C/TLFW102C-IOC-01App/src/TLFW102C-IOC-01Main.cpp
  TLFW102C/TLFW102C-IOC-01App/src/build.mak
  TLFW102C/TLFW102C-IOC-02App/Db/Makefile
  TLFW102C/TLFW102C-IOC-02App/Makefile
  TLFW102C/TLFW102C-IOC-02App/src/Makefile
  TLFW102C/TLFW102C-IOC-02App/src/TLFW102C-IOC-02Main.cpp
  TLFW102C/TLFW102C-IOC-03App/Db/Makefile
  TLFW102C/TLFW102C-IOC-03App/Makefile
  TLFW102C/TLFW102C-IOC-03App/src/Makefile
  TLFW102C/TLFW102C-IOC-03App/src/TLFW102C-IOC-03Main.cpp
  TLFW102C/configure/CONFIG
  TLFW102C/configure/CONFIG_SITE
  TLFW102C/configure/Makefile
  TLFW102C/configure/RELEASE
  TLFW102C/configure/RULES
  TLFW102C/configure/RULES.ioc
  TLFW102C/configure/RULES_DIRS
  TLFW102C/configure/RULES_TOP
  TLFW102C/iocBoot/Makefile
  TLFW102C/iocBoot/iocTLFW102C-IOC-01/Makefile
  TLFW102C/iocBoot/iocTLFW102C-IOC-01/config.xml
  TLFW102C/iocBoot/iocTLFW102C-IOC-01/st-common.cmd
  TLFW102C/iocBoot/iocTLFW102C-IOC-01/st.cmd
  TLFW102C/iocBoot/iocTLFW102C-IOC-02/Makefile
  TLFW102C/iocBoot/iocTLFW102C-IOC-02/config.xml
  TLFW102C/iocBoot/iocTLFW102C-IOC-02/st.cmd
  TLFW102C/iocBoot/iocTLFW102C-IOC-03/Makefile
  TLFW102C/iocBoot/iocTLFW102C-IOC-03/config.xml
  TLFW102C/iocBoot/iocTLFW102C-IOC-03/st.cmd
Labels: size/XL

#894 Fix missing mysql library
  TLFW102C/TLFW102C-IOC-01App/src/build.mak
Labels: size/XS

#851 Add check_read record to periodically check RBV record, make read_restart a calcout to not proc READ record if RBV is in alarm
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Labels: size/S
