Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-05, with the labels that each got.

#850 fix table of motors energised icon for beckhoffs
  TC/TC-IOC-01App/Db/axis_monitors.db
Labels: size/S

#847 fix dmm40X0 ioc
  TEKDMM40X0/TEKDMM4040-IOC-01App/Db/devDMM40X0.db
  TEKDMM40X0/TEKDMM40X0-IOC-01App/Db/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-01App/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-01App/src/Makefile
  TEKDMM40X0/TEKDMM40X0-IOC-01App/src/TEKDMM40X0-IOC-01Main.cpp
  TEKDMM40X0/TEKDMM40X0-IOC-01App/src/build.mak
  TEKDMM40X0/configure/RELEASE
  TEKDMM40X0/iocBoot/iocTEKDMM4040-IOC-01/st.cmd
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-01/Makefile
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-01/config.xml
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-01/st-common.cmd
  TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-01/st.cmd
Labels: size/L

#852 Added missing EOL character
  LVREMOTE/LVREMOTE-IOC-01App/Db/lvremotetest.substitutions
Labels: size/XS

#854 remove template description
  LVREMOTE/iocBoot/iocLVREMOTE-IOC-01/config.xml
Labels: size/XS

#855 Ticket8345
  GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam.cmd
  GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd
Labels: size/M

#807 Add REMOTE_ON_SET macro
  KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
  KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
  ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
Labels: size/S

#857 Ticket8357 multiple caen crates
  CAENV895/iocBoot/iocCAENV895-IOC-01/config.xml
  CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd
Labels: size/M

#859 Add newline to errors printed to fix tests
  FERMCHOP/FERMCHOP-IOC-01App/src/fermi.cpp
Labels: size/XS
