Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-12, with the labels that each got.

#887 Remove use of MASTER_RELEASE
  INSTETC/configure/RELEASE
  PSCTRL/PSCTRL-IOC-01App/src/build.mak
  PSCTRL/configure/RELEASE
  RUNCTRL/configure/RELEASE
Labels: size/M

#895 fix LKUP macro regex
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
Labels: size/XS

#896 correct pattern
  MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
Labels: size/XS

#897 Add static link library
  PSCTRL/PSCTRL-IOC-01App/src/build.mak
Labels: size/XS

#898 add quotation marks in eurotherm db to fix system tests
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Labels: size/XS

#900 Delete HIFIMAG ioc (lvdcom)
  HIFIMAG/HIFIMAG-IOC-01App/Db/Makefile
  HIFIMAG/HIFIMAG-IOC-01App/Db/controls.db
  HIFIMAG/HIFIMAG-IOC-01App/Makefile
  HIFIMAG/HIFIMAG-IOC-01App/protocol/Makefile
  HIFIMAG/HIFIMAG-IOC-01App/protocol/lv_controls.xml
  HIFIMAG/HIFIMAG-IOC-01App/src/HIFIMAG-IOC-01Main.cpp
  HIFIMAG/HIFIMAG-IOC-01App/src/Makefile
  HIFIMAG/HIFIMAG-IOC-01App/src/build.mak
  HIFIMAG/Makefile
  HIFIMAG/configure/CONFIG
  HIFIMAG/configure/CONFIG_SITE
  HIFIMAG/configure/Makefile
  HIFIMAG/configure/RELEASE
  HIFIMAG/configure/RULES
  HIFIMAG/configure/RULES.ioc
  HIFIMAG/configure/RULES_DIRS
  HIFIMAG/configure/RULES_TOP
  HIFIMAG/iocBoot/Makefile
  HIFIMAG/iocBoot/iocHIFIMAG-IOC-01/Makefile
  HIFIMAG/iocBoot/iocHIFIMAG-IOC-01/config.xml
  HIFIMAG/iocBoot/iocHIFIMAG-IOC-01/st.cmd
  Makefile
Labels: size/XL

#901 Update devEurothrm.db
  EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Labels: size/XS

#899 Added ioc for the new focus intellgient picometer
  Makefile
  NFIPM/Makefile
  NFIPM/NFIPM-IOC-01App/Makefile
  NFIPM/NFIPM-IOC-01App/db/Makefile
  NFIPM/NFIPM-IOC-01App/db/motor.substitutions
  NFIPM/NFIPM-IOC-01App/db/motorSim.substitutions
  NFIPM/NFIPM-IOC-01App/src/Makefile
  NFIPM/NFIPM-IOC-01App/src/NFIPM-IOC-01Main.cpp
  NFIPM/NFIPM-IOC-01App/src/build.mak
  NFIPM/configure/CONFIG
  NFIPM/configure/CONFIG_SITE
  NFIPM/configure/Makefile
  NFIPM/configure/RELEASE
  NFIPM/configure/RULES
  NFIPM/configure/RULES.ioc
  NFIPM/configure/RULES_DIRS
  NFIPM/configure/RULES_TOP
  NFIPM/iocBoot/Makefile
  NFIPM/iocBoot/iocNFIPM-IOC-01/Makefile
  NFIPM/iocBoot/iocNFIPM-IOC-01/axes.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/config.xml
  NFIPM/iocBoot/iocNFIPM-IOC-01/jaws.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/motionsetpoints.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/st-axes.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/st-common.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/st-ctrl.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/st-max-axis.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/st-motor.cmd
  NFIPM/iocBoot/iocNFIPM-IOC-01/st.cmd
Labels: size/XL

#893 Use / to avoid trailing \ warning
  MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd
Labels: size/XS
