Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-01, with the labels that each got.

#821 Refactor LSI startup
  LSICORR/iocBoot/iocLSICORR-IOC-01/Makefile
  LSICORR/iocBoot/iocLSICORR-IOC-01/dllPath.bat
  LSICORR/iocBoot/iocLSICORR-IOC-01/runIOC.bat
  LSICORR/iocBoot/iocLSICORR-IOC-02/Makefile
  LSICORR/iocBoot/iocLSICORR-IOC-02/dllPath.bat
  LSICORR/iocBoot/iocLSICORR-IOC-02/runIOC.bat
Labels: size/M

#824 Add NEEDLE_VALVE_TOGGLE_WRITE macro
  EUROTHRM/EUROTHRM-IOC-01App/Db/automaticNeedleValve.db
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/config.xml
  EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
Labels: size/XS

#823 Ticket8105
  GENICAM/GENICAM-IOC-01App/Db/Makefile
  GENICAM/GENICAM-IOC-01App/Makefile
  GENICAM/GENICAM-IOC-01App/protocol/Makefile
  GENICAM/GENICAM-IOC-01App/src/GENICAM-IOC-01Main.cpp
  GENICAM/GENICAM-IOC-01App/src/Makefile
  GENICAM/GENICAM-IOC-01App/src/build.mak
  GENICAM/Makefile
  GENICAM/configure/CONFIG
  GENICAM/configure/CONFIG_SITE
  GENICAM/configure/Makefile
  GENICAM/configure/RELEASE
  GENICAM/configure/RULES
  GENICAM/configure/RULES.ioc
  GENICAM/configure/RULES_DIRS
  GENICAM/configure/RULES_TOP
  GENICAM/iocBoot/Makefile
  GENICAM/iocBoot/iocGENICAM-IOC-01/Makefile
  GENICAM/iocBoot/iocGENICAM-IOC-01/config.xml
  GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam.cmd
  GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd
  GENICAM/iocBoot/iocGENICAM-IOC-01/st-common.cmd
  GENICAM/iocBoot/iocGENICAM-IOC-01/st.cmd
  GENICAM/iocBoot/iocGENICAM-IOC-01/st.cmd.base
Labels: size/XL

#826 add stuff in IOC for allowing 2 TC IOCs
  TC/TC-IOC-02App/Db/Makefile
  TC/TC-IOC-02App/Makefile
  TC/TC-IOC-02App/protocol/Makefile
  TC/TC-IOC-02App/src/Makefile
  TC/TC-IOC-02App/src/TC-IOC-02Main.cpp
  TC/iocBoot/iocTC-IOC-02/Makefile
  TC/iocBoot/iocTC-IOC-02/TC_02_settings.req
  TC/iocBoot/iocTC-IOC-02/config.xml
  TC/iocBoot/iocTC-IOC-02/st.cmd
Labels: size/L
