Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2024-04, with the labels that each got.

#841 Ticket8210 add ioc lndyisw
  LNDYISW/LNDYISW-IOC-01App/Db/Makefile
  LNDYISW/LNDYISW-IOC-01App/Makefile
  LNDYISW/LNDYISW-IOC-01App/src/LNDYISW-IOC-01Main.cpp
  LNDYISW/LNDYISW-IOC-01App/src/Makefile
  LNDYISW/LNDYISW-IOC-01App/src/build.mak
  LNDYISW/LNDYISW-IOC-02App/Db/Makefile
  LNDYISW/LNDYISW-IOC-02App/Makefile
  LNDYISW/LNDYISW-IOC-02App/src/LNDYISW-IOC-02Main.cpp
  LNDYISW/LNDYISW-IOC-02App/src/Makefile
  LNDYISW/Makefile
  LNDYISW/configure/CONFIG
  LNDYISW/configure/CONFIG_SITE
  LNDYISW/configure/Makefile
  LNDYISW/configure/RELEASE
  LNDYISW/configure/RULES
  LNDYISW/configure/RULES.ioc
  LNDYISW/configure/RULES_DIRS
  LNDYISW/configure/RULES_TOP
  LNDYISW/iocBoot/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-01/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-01/config.xml
  LNDYISW/iocBoot/iocLNDYISW-IOC-01/st-common.cmd
  LNDYISW/iocBoot/iocLNDYISW-IOC-01/st.cmd
  LNDYISW/iocBoot/iocLNDYISW-IOC-02/Makefile
  LNDYISW/iocBoot/iocLNDYISW-IOC-02/config.xml
  LNDYISW/iocBoot/iocLNDYISW-IOC-02/st.cmd
  Makefile
Labels: size/XL

#838 Updates for NCINDG
  NCINDG/iocBoot/iocNCINDG-IOC-01/config.xml
  NCINDG/iocBoot/iocNCINDG-IOC-01/digitiser-params Backup02Mar2023.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/digitiser-params.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/digitiser-paramsBackup06Mar2023.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/hdf5-files.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/hdf5_attributes.xml
  NCINDG/iocBoot/iocNCINDG-IOC-01/hdf5_layout.xml
  NCINDG/iocBoot/iocNCINDG-IOC-01/liveview.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/postiocinit-dig.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/st-common.cmd
  NCINDG/iocBoot/iocNCINDG-IOC-01/st-dig.cmd
Labels: size/XL

#844 Add link to build.mak
  LNDYISW/LNDYISW-IOC-01App/src/build.mak
Labels: size/XS

#843 Ticket_8284_Allow_certain_values_to_be_editable_without_restarting_IOC
  MCLEN/MCLEN-IOC-01App/Db/mclen_motor_extra.db
  MCLEN/MCLEN-IOC-01App/Db/motor.substitutions
  MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
Labels: size/XS

#846 Default value for MOTOR_ASG also added to st-motor.cmd
  MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
Labels: size/XS

#835 Add IOC directory for PS300
  Makefile
  PS300/Makefile
  PS300/PS300-IOC-01App/Db/Makefile
  PS300/PS300-IOC-01App/Makefile
  PS300/PS300-IOC-01App/src/Makefile
  PS300/PS300-IOC-01App/src/PS300-IOC-01Main.cpp
  PS300/PS300-IOC-01App/src/build.mak
  PS300/configure/CONFIG
  PS300/configure/CONFIG_SITE
  PS300/configure/Makefile
  PS300/configure/RELEASE
  PS300/configure/RULES
  PS300/configure/RULES.ioc
  PS300/configure/RULES_DIRS
  PS300/configure/RULES_TOP
  PS300/iocBoot/Makefile
  PS300/iocBoot/iocPS300-IOC-01/Makefile
  PS300/iocBoot/iocPS300-IOC-01/config.xml
  PS300/iocBoot/iocPS300-IOC-01/st-common.cmd
  PS300/iocBoot/iocPS300-IOC-01/st.cmd
Labels: size/L
