Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2025-09, with the labels that each got.

#935 Correct regex to allow default value to pass
  NGEM/iocBoot/iocNGEM-IOC-01/config.xml
Labels: size/XS

#934 Adding macros to config st.cmd
  HVCAEN/iocBoot/iocHVCAEN-IOC-01/config.xml
  HVCAEN/iocBoot/iocHVCAEN-IOC-01/st.cmd
  HVCAEN/iocBoot/iocHVCAENSIM-IOC-01/config.xml
  HVCAEN/iocBoot/iocHVCAENSIM-IOC-01/st.cmd
Labels: size/S

#939 Ticket8766 Larmor magnet ioc current
  DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/NSV1.db
Labels: size/M
