Repository ISISComputingGroup/EPICS-ioc, pull requests merged in 2025-01, with the labels that each got.

#903 Litronlasertiming#6090
  DG645/iocBoot/iocDG645-IOC-01/config.xml
  DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
Labels: size/XS

#906 Ticket8413 add IOC Anton-Paar L-DENS 3300
  LDEN3300/LDEN3300-IOC-01App/Makefile
  LDEN3300/LDEN3300-IOC-01App/src/LDEN3300-IOC-01Main.cpp
  LDEN3300/LDEN3300-IOC-01App/src/Makefile
  LDEN3300/LDEN3300-IOC-01App/src/build.mak
  LDEN3300/LDEN3300-IOC-02App/Db/Makefile
  LDEN3300/LDEN3300-IOC-02App/Makefile
  LDEN3300/LDEN3300-IOC-02App/src/LDEN3300-IOC-02Main.cpp
  LDEN3300/LDEN3300-IOC-02App/src/Makefile
  LDEN3300/LDEN3300-IOC-03App/Db/Makefile
  LDEN3300/LDEN3300-IOC-03App/Makefile
  LDEN3300/LDEN3300-IOC-03App/src/LDEN3300-IOC-03Main.cpp
  LDEN3300/LDEN3300-IOC-03App/src/Makefile
  LDEN3300/LDEN3300-IOC-04App/Db/Makefile
  LDEN3300/LDEN3300-IOC-04App/Makefile
  LDEN3300/LDEN3300-IOC-04App/src/LDEN3300-IOC-04Main.cpp
  LDEN3300/LDEN3300-IOC-04App/src/Makefile
  LDEN3300/Makefile
  LDEN3300/configure/CONFIG
  LDEN3300/configure/CONFIG_SITE
  LDEN3300/configure/Makefile
  LDEN3300/configure/RELEASE
  LDEN3300/configure/RULES
  LDEN3300/configure/RULES.ioc
  LDEN3300/configure/RULES_DIRS
  LDEN3300/configure/RULES_TOP
  LDEN3300/iocBoot/Makefile
  LDEN3300/iocBoot/iocLDEN3300-IOC-01/Makefile
  LDEN3300/iocBoot/iocLDEN3300-IOC-01/config.xml
  LDEN3300/iocBoot/iocLDEN3300-IOC-01/st-common.cmd
  LDEN3300/iocBoot/iocLDEN3300-IOC-01/st.cmd
  LDEN3300/iocBoot/iocLDEN3300-IOC-02/Makefile
  LDEN3300/iocBoot/iocLDEN3300-IOC-02/config.xml
  LDEN3300/iocBoot/iocLDEN3300-IOC-02/st.cmd
  LDEN3300/iocBoot/iocLDEN3300-IOC-03/Makefile
  LDEN3300/iocBoot/iocLDEN3300-IOC-03/config.xml
  LDEN3300/iocBoot/iocLDEN3300-IOC-03/st.cmd
  LDEN3300/iocBoot/iocLDEN3300-IOC-04/Makefile
  LDEN3300/iocBoot/iocLDEN3300-IOC-04/config.xml
  LDEN3300/iocBoot/iocLDEN3300-IOC-04/st.cmd
  Makefile
Labels: size/XL

#905 Hifi ZF
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/config.xml
  G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/st-common.cmd
  ZFHIFI/Makefile
  ZFHIFI/ZFHIFI-IOC-01App/Makefile
  ZFHIFI/ZFHIFI-IOC-01App/src/Makefile
  ZFHIFI/ZFHIFI-IOC-01App/src/ZFHIFI-IOC-01Main.cpp
  ZFHIFI/ZFHIFI-IOC-01App/src/build.mak
  ZFHIFI/configure/CONFIG
  ZFHIFI/configure/CONFIG_SITE
  ZFHIFI/configure/Makefile
  ZFHIFI/configure/RELEASE
  ZFHIFI/configure/RULES
  ZFHIFI/configure/RULES.ioc
  ZFHIFI/configure/RULES_DIRS
  ZFHIFI/configure/RULES_TOP
  ZFHIFI/iocBoot/Makefile
  ZFHIFI/iocBoot/iocZFHIFI-IOC-01/Makefile
  ZFHIFI/iocBoot/iocZFHIFI-IOC-01/config.xml
  ZFHIFI/iocBoot/iocZFHIFI-IOC-01/st.cmd
Labels: size/L

#902 Add Litron IOC
  LITRON/.gitignore
  LITRON/LITRON-IOC-01App/Db/Makefile
  LITRON/LITRON-IOC-01App/Makefile
  LITRON/LITRON-IOC-01App/src/LITRON-IOC-01Main.cpp
  LITRON/LITRON-IOC-01App/src/Makefile
  LITRON/LITRON-IOC-01App/src/build.mak
  LITRON/Makefile
  LITRON/configure/CONFIG
  LITRON/configure/CONFIG_SITE
  LITRON/configure/Makefile
  LITRON/configure/RELEASE
  LITRON/configure/RULES
  LITRON/configure/RULES.ioc
  LITRON/configure/RULES_DIRS
  LITRON/configure/RULES_TOP
  LITRON/iocBoot/Makefile
  LITRON/iocBoot/iocLITRON-IOC-01/Makefile
  LITRON/iocBoot/iocLITRON-IOC-01/config.xml
  LITRON/iocBoot/iocLITRON-IOC-01/st-common.cmd
  LITRON/iocBoot/iocLITRON-IOC-01/st.cmd
  Makefile
Labels: size/L

#908 Set initial wait for conenction
  PSCTRL/iocBoot/iocPSCTRL-IOC-01/st.cmd
Labels: size/XS

#911 copy pearl cam settings from ndxpearl
  GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd
Labels: size/XS
